// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.0
// source: tailbus/v1/transport.proto

package transportpb

import (
	messagepb "github.com/alexanderfrey/tailbus/api/messagepb"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_tailbus_v1_transport_proto protoreflect.FileDescriptor

const file_tailbus_v1_transport_proto_rawDesc = "" +
	"\n" +
	"\x1atailbus/v1/transport.proto\x12\n" +
	"tailbus.v1\x1a\x19tailbus/v1/messages.proto2K\n" +
	"\rNodeTransport\x12:\n" +
	"\bExchange\x12\x14.tailbus.v1.Envelope\x1a\x14.tailbus.v1.Envelope(\x010\x01B2Z0github.com/alexanderfrey/tailbus/api/transportpbb\x06proto3"

var file_tailbus_v1_transport_proto_goTypes = []any{
	(*messagepb.Envelope)(nil), // 0: tailbus.v1.Envelope
}
var file_tailbus_v1_transport_proto_depIdxs = []int32{
	0, // 0: tailbus.v1.NodeTransport.Exchange:input_type -> tailbus.v1.Envelope
	0, // 1: tailbus.v1.NodeTransport.Exchange:output_type -> tailbus.v1.Envelope
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_tailbus_v1_transport_proto_init() }
func file_tailbus_v1_transport_proto_init() {
	if File_tailbus_v1_transport_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_tailbus_v1_transport_proto_rawDesc), len(file_tailbus_v1_transport_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_tailbus_v1_transport_proto_goTypes,
		DependencyIndexes: file_tailbus_v1_transport_proto_depIdxs,
	}.Build()
	File_tailbus_v1_transport_proto = out.File
	file_tailbus_v1_transport_proto_goTypes = nil
	file_tailbus_v1_transport_proto_depIdxs = nil
}
