// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v7.34.0
// source: tailbus/v1/transport.proto

package transportpb

import (
	context "context"
	messagepb "github.com/alexanderfrey/tailbus/api/messagepb"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	NodeTransport_Exchange_FullMethodName = "/tailbus.v1.NodeTransport/Exchange"
)

// NodeTransportClient is the client API for NodeTransport service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type NodeTransportClient interface {
	Exchange(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[messagepb.Envelope, messagepb.Envelope], error)
}

type nodeTransportClient struct {
	cc grpc.ClientConnInterface
}

func NewNodeTransportClient(cc grpc.ClientConnInterface) NodeTransportClient {
	return &nodeTransportClient{cc}
}

func (c *nodeTransportClient) Exchange(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[messagepb.Envelope, messagepb.Envelope], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &NodeTransport_ServiceDesc.Streams[0], NodeTransport_Exchange_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[messagepb.Envelope, messagepb.Envelope]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type NodeTransport_ExchangeClient = grpc.BidiStreamingClient[messagepb.Envelope, messagepb.Envelope]

// NodeTransportServer is the server API for NodeTransport service.
// All implementations must embed UnimplementedNodeTransportServer
// for forward compatibility.
type NodeTransportServer interface {
	Exchange(grpc.BidiStreamingServer[messagepb.Envelope, messagepb.Envelope]) error
	mustEmbedUnimplementedNodeTransportServer()
}

// UnimplementedNodeTransportServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedNodeTransportServer struct{}

func (UnimplementedNodeTransportServer) Exchange(grpc.BidiStreamingServer[messagepb.Envelope, messagepb.Envelope]) error {
	return status.Error(codes.Unimplemented, "method Exchange not implemented")
}
func (UnimplementedNodeTransportServer) mustEmbedUnimplementedNodeTransportServer() {}
func (UnimplementedNodeTransportServer) testEmbeddedByValue()                       {}

// UnsafeNodeTransportServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to NodeTransportServer will
// result in compilation errors.
type UnsafeNodeTransportServer interface {
	mustEmbedUnimplementedNodeTransportServer()
}

func RegisterNodeTransportServer(s grpc.ServiceRegistrar, srv NodeTransportServer) {
	// If the following call panics, it indicates UnimplementedNodeTransportServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&NodeTransport_ServiceDesc, srv)
}

func _NodeTransport_Exchange_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(NodeTransportServer).Exchange(&grpc.GenericServerStream[messagepb.Envelope, messagepb.Envelope]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type NodeTransport_ExchangeServer = grpc.BidiStreamingServer[messagepb.Envelope, messagepb.Envelope]

// NodeTransport_ServiceDesc is the grpc.ServiceDesc for NodeTransport service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var NodeTransport_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "tailbus.v1.NodeTransport",
	HandlerType: (*NodeTransportServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Exchange",
			Handler:       _NodeTransport_Exchange_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "tailbus/v1/transport.proto",
}
