// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v4.25.3
// source: tailbus/v1/messages.proto

package messagepb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EnvelopeType int32

const (
	EnvelopeType_ENVELOPE_TYPE_UNSPECIFIED     EnvelopeType = 0
	EnvelopeType_ENVELOPE_TYPE_MESSAGE         EnvelopeType = 1
	EnvelopeType_ENVELOPE_TYPE_SESSION_OPEN    EnvelopeType = 2
	EnvelopeType_ENVELOPE_TYPE_SESSION_RESOLVE EnvelopeType = 3
	EnvelopeType_ENVELOPE_TYPE_ACK             EnvelopeType = 4
)

// Enum value maps for EnvelopeType.
var (
	EnvelopeType_name = map[int32]string{
		0: "ENVELOPE_TYPE_UNSPECIFIED",
		1: "ENVELOPE_TYPE_MESSAGE",
		2: "ENVELOPE_TYPE_SESSION_OPEN",
		3: "ENVELOPE_TYPE_SESSION_RESOLVE",
		4: "ENVELOPE_TYPE_ACK",
	}
	EnvelopeType_value = map[string]int32{
		"ENVELOPE_TYPE_UNSPECIFIED":     0,
		"ENVELOPE_TYPE_MESSAGE":         1,
		"ENVELOPE_TYPE_SESSION_OPEN":    2,
		"ENVELOPE_TYPE_SESSION_RESOLVE": 3,
		"ENVELOPE_TYPE_ACK":             4,
	}
)

func (x EnvelopeType) Enum() *EnvelopeType {
	p := new(EnvelopeType)
	*p = x
	return p
}

func (x EnvelopeType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EnvelopeType) Descriptor() protoreflect.EnumDescriptor {
	return file_tailbus_v1_messages_proto_enumTypes[0].Descriptor()
}

func (EnvelopeType) Type() protoreflect.EnumType {
	return &file_tailbus_v1_messages_proto_enumTypes[0]
}

func (x EnvelopeType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use EnvelopeType.Descriptor instead.
func (EnvelopeType) EnumDescriptor() ([]byte, []int) {
	return file_tailbus_v1_messages_proto_rawDescGZIP(), []int{0}
}

type Envelope struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	MessageId      string                 `protobuf:"bytes,1,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	SessionId      string                 `protobuf:"bytes,2,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	FromHandle     string                 `protobuf:"bytes,3,opt,name=from_handle,json=fromHandle,proto3" json:"from_handle,omitempty"`
	ToHandle       string                 `protobuf:"bytes,4,opt,name=to_handle,json=toHandle,proto3" json:"to_handle,omitempty"`
	Payload        []byte                 `protobuf:"bytes,5,opt,name=payload,proto3" json:"payload,omitempty"`
	ContentType    string                 `protobuf:"bytes,6,opt,name=content_type,json=contentType,proto3" json:"content_type,omitempty"`
	SentAtUnix     int64                  `protobuf:"varint,7,opt,name=sent_at_unix,json=sentAtUnix,proto3" json:"sent_at_unix,omitempty"`
	Type           EnvelopeType           `protobuf:"varint,8,opt,name=type,proto3,enum=tailbus.v1.EnvelopeType" json:"type,omitempty"`
	TraceId        string                 `protobuf:"bytes,9,opt,name=trace_id,json=traceId,proto3" json:"trace_id,omitempty"`
	Sequence       uint64                 `protobuf:"varint,10,opt,name=sequence,proto3" json:"sequence,omitempty"`
	AckId          string                 `protobuf:"bytes,11,opt,name=ack_id,json=ackId,proto3" json:"ack_id,omitempty"`
	RelayTargetKey []byte                 `protobuf:"bytes,12,opt,name=relay_target_key,json=relayTargetKey,proto3" json:"relay_target_key,omitempty"` // Target node pubkey (set by sender when routing via relay)
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Envelope) Reset() {
	*x = Envelope{}
	mi := &file_tailbus_v1_messages_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Envelope) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Envelope) ProtoMessage() {}

func (x *Envelope) ProtoReflect() protoreflect.Message {
	mi := &file_tailbus_v1_messages_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Envelope.ProtoReflect.Descriptor instead.
func (*Envelope) Descriptor() ([]byte, []int) {
	return file_tailbus_v1_messages_proto_rawDescGZIP(), []int{0}
}

func (x *Envelope) GetMessageId() string {
	if x != nil {
		return x.MessageId
	}
	return ""
}

func (x *Envelope) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *Envelope) GetFromHandle() string {
	if x != nil {
		return x.FromHandle
	}
	return ""
}

func (x *Envelope) GetToHandle() string {
	if x != nil {
		return x.ToHandle
	}
	return ""
}

func (x *Envelope) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *Envelope) GetContentType() string {
	if x != nil {
		return x.ContentType
	}
	return ""
}

func (x *Envelope) GetSentAtUnix() int64 {
	if x != nil {
		return x.SentAtUnix
	}
	return 0
}

func (x *Envelope) GetType() EnvelopeType {
	if x != nil {
		return x.Type
	}
	return EnvelopeType_ENVELOPE_TYPE_UNSPECIFIED
}

func (x *Envelope) GetTraceId() string {
	if x != nil {
		return x.TraceId
	}
	return ""
}

func (x *Envelope) GetSequence() uint64 {
	if x != nil {
		return x.Sequence
	}
	return 0
}

func (x *Envelope) GetAckId() string {
	if x != nil {
		return x.AckId
	}
	return ""
}

func (x *Envelope) GetRelayTargetKey() []byte {
	if x != nil {
		return x.RelayTargetKey
	}
	return nil
}

type CommandSpec struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Name             string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Description      string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	ParametersSchema string                 `protobuf:"bytes,3,opt,name=parameters_schema,json=parametersSchema,proto3" json:"parameters_schema,omitempty"` // optional JSON Schema
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *CommandSpec) Reset() {
	*x = CommandSpec{}
	mi := &file_tailbus_v1_messages_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommandSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommandSpec) ProtoMessage() {}

func (x *CommandSpec) ProtoReflect() protoreflect.Message {
	mi := &file_tailbus_v1_messages_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommandSpec.ProtoReflect.Descriptor instead.
func (*CommandSpec) Descriptor() ([]byte, []int) {
	return file_tailbus_v1_messages_proto_rawDescGZIP(), []int{1}
}

func (x *CommandSpec) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CommandSpec) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CommandSpec) GetParametersSchema() string {
	if x != nil {
		return x.ParametersSchema
	}
	return ""
}

type ServiceManifest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Description   string                 `protobuf:"bytes,1,opt,name=description,proto3" json:"description,omitempty"`
	Commands      []*CommandSpec         `protobuf:"bytes,2,rep,name=commands,proto3" json:"commands,omitempty"`
	Tags          []string               `protobuf:"bytes,3,rep,name=tags,proto3" json:"tags,omitempty"`
	Version       string                 `protobuf:"bytes,4,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServiceManifest) Reset() {
	*x = ServiceManifest{}
	mi := &file_tailbus_v1_messages_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServiceManifest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceManifest) ProtoMessage() {}

func (x *ServiceManifest) ProtoReflect() protoreflect.Message {
	mi := &file_tailbus_v1_messages_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServiceManifest.ProtoReflect.Descriptor instead.
func (*ServiceManifest) Descriptor() ([]byte, []int) {
	return file_tailbus_v1_messages_proto_rawDescGZIP(), []int{2}
}

func (x *ServiceManifest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *ServiceManifest) GetCommands() []*CommandSpec {
	if x != nil {
		return x.Commands
	}
	return nil
}

func (x *ServiceManifest) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *ServiceManifest) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

var File_tailbus_v1_messages_proto protoreflect.FileDescriptor

const file_tailbus_v1_messages_proto_rawDesc = "" +
	"\n" +
	"\x19tailbus/v1/messages.proto\x12\n" +
	"tailbus.v1\"\x8b\x03\n" +
	"\bEnvelope\x12\x1d\n" +
	"\n" +
	"message_id\x18\x01 \x01(\tR\tmessageId\x12\x1d\n" +
	"\n" +
	"session_id\x18\x02 \x01(\tR\tsessionId\x12\x1f\n" +
	"\vfrom_handle\x18\x03 \x01(\tR\n" +
	"fromHandle\x12\x1b\n" +
	"\tto_handle\x18\x04 \x01(\tR\btoHandle\x12\x18\n" +
	"\apayload\x18\x05 \x01(\fR\apayload\x12!\n" +
	"\fcontent_type\x18\x06 \x01(\tR\vcontentType\x12 \n" +
	"\fsent_at_unix\x18\a \x01(\x03R\n" +
	"sentAtUnix\x12,\n" +
	"\x04type\x18\b \x01(\x0e2\x18.tailbus.v1.EnvelopeTypeR\x04type\x12\x19\n" +
	"\btrace_id\x18\t \x01(\tR\atraceId\x12\x1a\n" +
	"\bsequence\x18\n" +
	" \x01(\x04R\bsequence\x12\x15\n" +
	"\x06ack_id\x18\v \x01(\tR\x05ackId\x12(\n" +
	"\x10relay_target_key\x18\f \x01(\fR\x0erelayTargetKey\"p\n" +
	"\vCommandSpec\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12+\n" +
	"\x11parameters_schema\x18\x03 \x01(\tR\x10parametersSchema\"\x96\x01\n" +
	"\x0fServiceManifest\x12 \n" +
	"\vdescription\x18\x01 \x01(\tR\vdescription\x123\n" +
	"\bcommands\x18\x02 \x03(\v2\x17.tailbus.v1.CommandSpecR\bcommands\x12\x12\n" +
	"\x04tags\x18\x03 \x03(\tR\x04tags\x12\x18\n" +
	"\aversion\x18\x04 \x01(\tR\aversion*\xa2\x01\n" +
	"\fEnvelopeType\x12\x1d\n" +
	"\x19ENVELOPE_TYPE_UNSPECIFIED\x10\x00\x12\x19\n" +
	"\x15ENVELOPE_TYPE_MESSAGE\x10\x01\x12\x1e\n" +
	"\x1aENVELOPE_TYPE_SESSION_OPEN\x10\x02\x12!\n" +
	"\x1dENVELOPE_TYPE_SESSION_RESOLVE\x10\x03\x12\x15\n" +
	"\x11ENVELOPE_TYPE_ACK\x10\x04B0Z.github.com/alexanderfrey/tailbus/api/messagepbb\x06proto3"

var (
	file_tailbus_v1_messages_proto_rawDescOnce sync.Once
	file_tailbus_v1_messages_proto_rawDescData []byte
)

func file_tailbus_v1_messages_proto_rawDescGZIP() []byte {
	file_tailbus_v1_messages_proto_rawDescOnce.Do(func() {
		file_tailbus_v1_messages_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_tailbus_v1_messages_proto_rawDesc), len(file_tailbus_v1_messages_proto_rawDesc)))
	})
	return file_tailbus_v1_messages_proto_rawDescData
}

var file_tailbus_v1_messages_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_tailbus_v1_messages_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_tailbus_v1_messages_proto_goTypes = []any{
	(EnvelopeType)(0),       // 0: tailbus.v1.EnvelopeType
	(*Envelope)(nil),        // 1: tailbus.v1.Envelope
	(*CommandSpec)(nil),     // 2: tailbus.v1.CommandSpec
	(*ServiceManifest)(nil), // 3: tailbus.v1.ServiceManifest
}
var file_tailbus_v1_messages_proto_depIdxs = []int32{
	0, // 0: tailbus.v1.Envelope.type:type_name -> tailbus.v1.EnvelopeType
	2, // 1: tailbus.v1.ServiceManifest.commands:type_name -> tailbus.v1.CommandSpec
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_tailbus_v1_messages_proto_init() }
func file_tailbus_v1_messages_proto_init() {
	if File_tailbus_v1_messages_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_tailbus_v1_messages_proto_rawDesc), len(file_tailbus_v1_messages_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_tailbus_v1_messages_proto_goTypes,
		DependencyIndexes: file_tailbus_v1_messages_proto_depIdxs,
		EnumInfos:         file_tailbus_v1_messages_proto_enumTypes,
		MessageInfos:      file_tailbus_v1_messages_proto_msgTypes,
	}.Build()
	File_tailbus_v1_messages_proto = out.File
	file_tailbus_v1_messages_proto_goTypes = nil
	file_tailbus_v1_messages_proto_depIdxs = nil
}
