// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v7.34.0
// source: tailbus/v1/coord.proto

package coordpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	CoordinationAPI_RegisterNode_FullMethodName = "/tailbus.v1.CoordinationAPI/RegisterNode"
	CoordinationAPI_WatchPeerMap_FullMethodName = "/tailbus.v1.CoordinationAPI/WatchPeerMap"
	CoordinationAPI_LookupHandle_FullMethodName = "/tailbus.v1.CoordinationAPI/LookupHandle"
	CoordinationAPI_Heartbeat_FullMethodName    = "/tailbus.v1.CoordinationAPI/Heartbeat"
)

// CoordinationAPIClient is the client API for CoordinationAPI service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CoordinationAPIClient interface {
	RegisterNode(ctx context.Context, in *RegisterNodeRequest, opts ...grpc.CallOption) (*RegisterNodeResponse, error)
	WatchPeerMap(ctx context.Context, in *WatchPeerMapRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[PeerMapUpdate], error)
	LookupHandle(ctx context.Context, in *LookupHandleRequest, opts ...grpc.CallOption) (*LookupHandleResponse, error)
	Heartbeat(ctx context.Context, in *HeartbeatRequest, opts ...grpc.CallOption) (*HeartbeatResponse, error)
}

type coordinationAPIClient struct {
	cc grpc.ClientConnInterface
}

func NewCoordinationAPIClient(cc grpc.ClientConnInterface) CoordinationAPIClient {
	return &coordinationAPIClient{cc}
}

func (c *coordinationAPIClient) RegisterNode(ctx context.Context, in *RegisterNodeRequest, opts ...grpc.CallOption) (*RegisterNodeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RegisterNodeResponse)
	err := c.cc.Invoke(ctx, CoordinationAPI_RegisterNode_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *coordinationAPIClient) WatchPeerMap(ctx context.Context, in *WatchPeerMapRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[PeerMapUpdate], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &CoordinationAPI_ServiceDesc.Streams[0], CoordinationAPI_WatchPeerMap_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[WatchPeerMapRequest, PeerMapUpdate]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type CoordinationAPI_WatchPeerMapClient = grpc.ServerStreamingClient[PeerMapUpdate]

func (c *coordinationAPIClient) LookupHandle(ctx context.Context, in *LookupHandleRequest, opts ...grpc.CallOption) (*LookupHandleResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LookupHandleResponse)
	err := c.cc.Invoke(ctx, CoordinationAPI_LookupHandle_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *coordinationAPIClient) Heartbeat(ctx context.Context, in *HeartbeatRequest, opts ...grpc.CallOption) (*HeartbeatResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HeartbeatResponse)
	err := c.cc.Invoke(ctx, CoordinationAPI_Heartbeat_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CoordinationAPIServer is the server API for CoordinationAPI service.
// All implementations must embed UnimplementedCoordinationAPIServer
// for forward compatibility.
type CoordinationAPIServer interface {
	RegisterNode(context.Context, *RegisterNodeRequest) (*RegisterNodeResponse, error)
	WatchPeerMap(*WatchPeerMapRequest, grpc.ServerStreamingServer[PeerMapUpdate]) error
	LookupHandle(context.Context, *LookupHandleRequest) (*LookupHandleResponse, error)
	Heartbeat(context.Context, *HeartbeatRequest) (*HeartbeatResponse, error)
	mustEmbedUnimplementedCoordinationAPIServer()
}

// UnimplementedCoordinationAPIServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedCoordinationAPIServer struct{}

func (UnimplementedCoordinationAPIServer) RegisterNode(context.Context, *RegisterNodeRequest) (*RegisterNodeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RegisterNode not implemented")
}
func (UnimplementedCoordinationAPIServer) WatchPeerMap(*WatchPeerMapRequest, grpc.ServerStreamingServer[PeerMapUpdate]) error {
	return status.Error(codes.Unimplemented, "method WatchPeerMap not implemented")
}
func (UnimplementedCoordinationAPIServer) LookupHandle(context.Context, *LookupHandleRequest) (*LookupHandleResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method LookupHandle not implemented")
}
func (UnimplementedCoordinationAPIServer) Heartbeat(context.Context, *HeartbeatRequest) (*HeartbeatResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Heartbeat not implemented")
}
func (UnimplementedCoordinationAPIServer) mustEmbedUnimplementedCoordinationAPIServer() {}
func (UnimplementedCoordinationAPIServer) testEmbeddedByValue()                         {}

// UnsafeCoordinationAPIServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CoordinationAPIServer will
// result in compilation errors.
type UnsafeCoordinationAPIServer interface {
	mustEmbedUnimplementedCoordinationAPIServer()
}

func RegisterCoordinationAPIServer(s grpc.ServiceRegistrar, srv CoordinationAPIServer) {
	// If the following call panics, it indicates UnimplementedCoordinationAPIServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&CoordinationAPI_ServiceDesc, srv)
}

func _CoordinationAPI_RegisterNode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterNodeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoordinationAPIServer).RegisterNode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CoordinationAPI_RegisterNode_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoordinationAPIServer).RegisterNode(ctx, req.(*RegisterNodeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CoordinationAPI_WatchPeerMap_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(WatchPeerMapRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(CoordinationAPIServer).WatchPeerMap(m, &grpc.GenericServerStream[WatchPeerMapRequest, PeerMapUpdate]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type CoordinationAPI_WatchPeerMapServer = grpc.ServerStreamingServer[PeerMapUpdate]

func _CoordinationAPI_LookupHandle_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LookupHandleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoordinationAPIServer).LookupHandle(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CoordinationAPI_LookupHandle_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoordinationAPIServer).LookupHandle(ctx, req.(*LookupHandleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CoordinationAPI_Heartbeat_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HeartbeatRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoordinationAPIServer).Heartbeat(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CoordinationAPI_Heartbeat_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoordinationAPIServer).Heartbeat(ctx, req.(*HeartbeatRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// CoordinationAPI_ServiceDesc is the grpc.ServiceDesc for CoordinationAPI service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CoordinationAPI_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "tailbus.v1.CoordinationAPI",
	HandlerType: (*CoordinationAPIServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RegisterNode",
			Handler:    _CoordinationAPI_RegisterNode_Handler,
		},
		{
			MethodName: "LookupHandle",
			Handler:    _CoordinationAPI_LookupHandle_Handler,
		},
		{
			MethodName: "Heartbeat",
			Handler:    _CoordinationAPI_Heartbeat_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "WatchPeerMap",
			Handler:       _CoordinationAPI_WatchPeerMap_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "tailbus/v1/coord.proto",
}
