// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v4.25.3
// source: tailbus/v1/coord.proto

package coordpb

import (
	messagepb "github.com/alexanderfrey/tailbus/api/messagepb"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RegisterNodeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	PublicKey     []byte                 `protobuf:"bytes,2,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"`
	AdvertiseAddr string                 `protobuf:"bytes,3,opt,name=advertise_addr,json=advertiseAddr,proto3" json:"advertise_addr,omitempty"`
	Handles       []string               `protobuf:"bytes,4,rep,name=handles,proto3" json:"handles,omitempty"`
	// Deprecated: Marked as deprecated in tailbus/v1/coord.proto.
	HandleDescriptions map[string]string                     `protobuf:"bytes,5,rep,name=handle_descriptions,json=handleDescriptions,proto3" json:"handle_descriptions,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	HandleManifests    map[string]*messagepb.ServiceManifest `protobuf:"bytes,6,rep,name=handle_manifests,json=handleManifests,proto3" json:"handle_manifests,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	IsRelay            bool                                  `protobuf:"varint,7,opt,name=is_relay,json=isRelay,proto3" json:"is_relay,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *RegisterNodeRequest) Reset() {
	*x = RegisterNodeRequest{}
	mi := &file_tailbus_v1_coord_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterNodeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterNodeRequest) ProtoMessage() {}

func (x *RegisterNodeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tailbus_v1_coord_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterNodeRequest.ProtoReflect.Descriptor instead.
func (*RegisterNodeRequest) Descriptor() ([]byte, []int) {
	return file_tailbus_v1_coord_proto_rawDescGZIP(), []int{0}
}

func (x *RegisterNodeRequest) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *RegisterNodeRequest) GetPublicKey() []byte {
	if x != nil {
		return x.PublicKey
	}
	return nil
}

func (x *RegisterNodeRequest) GetAdvertiseAddr() string {
	if x != nil {
		return x.AdvertiseAddr
	}
	return ""
}

func (x *RegisterNodeRequest) GetHandles() []string {
	if x != nil {
		return x.Handles
	}
	return nil
}

// Deprecated: Marked as deprecated in tailbus/v1/coord.proto.
func (x *RegisterNodeRequest) GetHandleDescriptions() map[string]string {
	if x != nil {
		return x.HandleDescriptions
	}
	return nil
}

func (x *RegisterNodeRequest) GetHandleManifests() map[string]*messagepb.ServiceManifest {
	if x != nil {
		return x.HandleManifests
	}
	return nil
}

func (x *RegisterNodeRequest) GetIsRelay() bool {
	if x != nil {
		return x.IsRelay
	}
	return false
}

type RegisterNodeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterNodeResponse) Reset() {
	*x = RegisterNodeResponse{}
	mi := &file_tailbus_v1_coord_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterNodeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterNodeResponse) ProtoMessage() {}

func (x *RegisterNodeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tailbus_v1_coord_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterNodeResponse.ProtoReflect.Descriptor instead.
func (*RegisterNodeResponse) Descriptor() ([]byte, []int) {
	return file_tailbus_v1_coord_proto_rawDescGZIP(), []int{1}
}

func (x *RegisterNodeResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *RegisterNodeResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type WatchPeerMapRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WatchPeerMapRequest) Reset() {
	*x = WatchPeerMapRequest{}
	mi := &file_tailbus_v1_coord_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WatchPeerMapRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WatchPeerMapRequest) ProtoMessage() {}

func (x *WatchPeerMapRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tailbus_v1_coord_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WatchPeerMapRequest.ProtoReflect.Descriptor instead.
func (*WatchPeerMapRequest) Descriptor() ([]byte, []int) {
	return file_tailbus_v1_coord_proto_rawDescGZIP(), []int{2}
}

func (x *WatchPeerMapRequest) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

type PeerMapUpdate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Peers         []*PeerInfo            `protobuf:"bytes,1,rep,name=peers,proto3" json:"peers,omitempty"`
	Version       int64                  `protobuf:"varint,2,opt,name=version,proto3" json:"version,omitempty"`
	Relays        []*RelayInfo           `protobuf:"bytes,3,rep,name=relays,proto3" json:"relays,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PeerMapUpdate) Reset() {
	*x = PeerMapUpdate{}
	mi := &file_tailbus_v1_coord_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PeerMapUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PeerMapUpdate) ProtoMessage() {}

func (x *PeerMapUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_tailbus_v1_coord_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PeerMapUpdate.ProtoReflect.Descriptor instead.
func (*PeerMapUpdate) Descriptor() ([]byte, []int) {
	return file_tailbus_v1_coord_proto_rawDescGZIP(), []int{3}
}

func (x *PeerMapUpdate) GetPeers() []*PeerInfo {
	if x != nil {
		return x.Peers
	}
	return nil
}

func (x *PeerMapUpdate) GetVersion() int64 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *PeerMapUpdate) GetRelays() []*RelayInfo {
	if x != nil {
		return x.Relays
	}
	return nil
}

type RelayInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	PublicKey     []byte                 `protobuf:"bytes,2,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"`
	Addr          string                 `protobuf:"bytes,3,opt,name=addr,proto3" json:"addr,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RelayInfo) Reset() {
	*x = RelayInfo{}
	mi := &file_tailbus_v1_coord_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RelayInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RelayInfo) ProtoMessage() {}

func (x *RelayInfo) ProtoReflect() protoreflect.Message {
	mi := &file_tailbus_v1_coord_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RelayInfo.ProtoReflect.Descriptor instead.
func (*RelayInfo) Descriptor() ([]byte, []int) {
	return file_tailbus_v1_coord_proto_rawDescGZIP(), []int{4}
}

func (x *RelayInfo) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *RelayInfo) GetPublicKey() []byte {
	if x != nil {
		return x.PublicKey
	}
	return nil
}

func (x *RelayInfo) GetAddr() string {
	if x != nil {
		return x.Addr
	}
	return ""
}

type PeerInfo struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	NodeId            string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	PublicKey         []byte                 `protobuf:"bytes,2,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"`
	AdvertiseAddr     string                 `protobuf:"bytes,3,opt,name=advertise_addr,json=advertiseAddr,proto3" json:"advertise_addr,omitempty"`
	Handles           []string               `protobuf:"bytes,4,rep,name=handles,proto3" json:"handles,omitempty"`
	LastHeartbeatUnix int64                  `protobuf:"varint,5,opt,name=last_heartbeat_unix,json=lastHeartbeatUnix,proto3" json:"last_heartbeat_unix,omitempty"`
	// Deprecated: Marked as deprecated in tailbus/v1/coord.proto.
	HandleDescriptions map[string]string                     `protobuf:"bytes,6,rep,name=handle_descriptions,json=handleDescriptions,proto3" json:"handle_descriptions,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	HandleManifests    map[string]*messagepb.ServiceManifest `protobuf:"bytes,7,rep,name=handle_manifests,json=handleManifests,proto3" json:"handle_manifests,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *PeerInfo) Reset() {
	*x = PeerInfo{}
	mi := &file_tailbus_v1_coord_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PeerInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PeerInfo) ProtoMessage() {}

func (x *PeerInfo) ProtoReflect() protoreflect.Message {
	mi := &file_tailbus_v1_coord_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PeerInfo.ProtoReflect.Descriptor instead.
func (*PeerInfo) Descriptor() ([]byte, []int) {
	return file_tailbus_v1_coord_proto_rawDescGZIP(), []int{5}
}

func (x *PeerInfo) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *PeerInfo) GetPublicKey() []byte {
	if x != nil {
		return x.PublicKey
	}
	return nil
}

func (x *PeerInfo) GetAdvertiseAddr() string {
	if x != nil {
		return x.AdvertiseAddr
	}
	return ""
}

func (x *PeerInfo) GetHandles() []string {
	if x != nil {
		return x.Handles
	}
	return nil
}

func (x *PeerInfo) GetLastHeartbeatUnix() int64 {
	if x != nil {
		return x.LastHeartbeatUnix
	}
	return 0
}

// Deprecated: Marked as deprecated in tailbus/v1/coord.proto.
func (x *PeerInfo) GetHandleDescriptions() map[string]string {
	if x != nil {
		return x.HandleDescriptions
	}
	return nil
}

func (x *PeerInfo) GetHandleManifests() map[string]*messagepb.ServiceManifest {
	if x != nil {
		return x.HandleManifests
	}
	return nil
}

type LookupHandleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Handle        string                 `protobuf:"bytes,1,opt,name=handle,proto3" json:"handle,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LookupHandleRequest) Reset() {
	*x = LookupHandleRequest{}
	mi := &file_tailbus_v1_coord_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LookupHandleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LookupHandleRequest) ProtoMessage() {}

func (x *LookupHandleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tailbus_v1_coord_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LookupHandleRequest.ProtoReflect.Descriptor instead.
func (*LookupHandleRequest) Descriptor() ([]byte, []int) {
	return file_tailbus_v1_coord_proto_rawDescGZIP(), []int{6}
}

func (x *LookupHandleRequest) GetHandle() string {
	if x != nil {
		return x.Handle
	}
	return ""
}

type LookupHandleResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Peer          *PeerInfo              `protobuf:"bytes,1,opt,name=peer,proto3" json:"peer,omitempty"`
	Found         bool                   `protobuf:"varint,2,opt,name=found,proto3" json:"found,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LookupHandleResponse) Reset() {
	*x = LookupHandleResponse{}
	mi := &file_tailbus_v1_coord_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LookupHandleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LookupHandleResponse) ProtoMessage() {}

func (x *LookupHandleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tailbus_v1_coord_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LookupHandleResponse.ProtoReflect.Descriptor instead.
func (*LookupHandleResponse) Descriptor() ([]byte, []int) {
	return file_tailbus_v1_coord_proto_rawDescGZIP(), []int{7}
}

func (x *LookupHandleResponse) GetPeer() *PeerInfo {
	if x != nil {
		return x.Peer
	}
	return nil
}

func (x *LookupHandleResponse) GetFound() bool {
	if x != nil {
		return x.Found
	}
	return false
}

type HeartbeatRequest struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	NodeId  string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	Handles []string               `protobuf:"bytes,2,rep,name=handles,proto3" json:"handles,omitempty"`
	// Deprecated: Marked as deprecated in tailbus/v1/coord.proto.
	HandleDescriptions map[string]string                     `protobuf:"bytes,3,rep,name=handle_descriptions,json=handleDescriptions,proto3" json:"handle_descriptions,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	HandleManifests    map[string]*messagepb.ServiceManifest `protobuf:"bytes,4,rep,name=handle_manifests,json=handleManifests,proto3" json:"handle_manifests,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *HeartbeatRequest) Reset() {
	*x = HeartbeatRequest{}
	mi := &file_tailbus_v1_coord_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatRequest) ProtoMessage() {}

func (x *HeartbeatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tailbus_v1_coord_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatRequest.ProtoReflect.Descriptor instead.
func (*HeartbeatRequest) Descriptor() ([]byte, []int) {
	return file_tailbus_v1_coord_proto_rawDescGZIP(), []int{8}
}

func (x *HeartbeatRequest) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *HeartbeatRequest) GetHandles() []string {
	if x != nil {
		return x.Handles
	}
	return nil
}

// Deprecated: Marked as deprecated in tailbus/v1/coord.proto.
func (x *HeartbeatRequest) GetHandleDescriptions() map[string]string {
	if x != nil {
		return x.HandleDescriptions
	}
	return nil
}

func (x *HeartbeatRequest) GetHandleManifests() map[string]*messagepb.ServiceManifest {
	if x != nil {
		return x.HandleManifests
	}
	return nil
}

type HeartbeatResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatResponse) Reset() {
	*x = HeartbeatResponse{}
	mi := &file_tailbus_v1_coord_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatResponse) ProtoMessage() {}

func (x *HeartbeatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tailbus_v1_coord_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatResponse.ProtoReflect.Descriptor instead.
func (*HeartbeatResponse) Descriptor() ([]byte, []int) {
	return file_tailbus_v1_coord_proto_rawDescGZIP(), []int{9}
}

func (x *HeartbeatResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

var File_tailbus_v1_coord_proto protoreflect.FileDescriptor

const file_tailbus_v1_coord_proto_rawDesc = "" +
	"\n" +
	"\x16tailbus/v1/coord.proto\x12\n" +
	"tailbus.v1\x1a\x19tailbus/v1/messages.proto\"\xa0\x04\n" +
	"\x13RegisterNodeRequest\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12\x1d\n" +
	"\n" +
	"public_key\x18\x02 \x01(\fR\tpublicKey\x12%\n" +
	"\x0eadvertise_addr\x18\x03 \x01(\tR\radvertiseAddr\x12\x18\n" +
	"\ahandles\x18\x04 \x03(\tR\ahandles\x12l\n" +
	"\x13handle_descriptions\x18\x05 \x03(\v27.tailbus.v1.RegisterNodeRequest.HandleDescriptionsEntryB\x02\x18\x01R\x12handleDescriptions\x12_\n" +
	"\x10handle_manifests\x18\x06 \x03(\v24.tailbus.v1.RegisterNodeRequest.HandleManifestsEntryR\x0fhandleManifests\x12\x19\n" +
	"\bis_relay\x18\a \x01(\bR\aisRelay\x1aE\n" +
	"\x17HandleDescriptionsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1a_\n" +
	"\x14HandleManifestsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x121\n" +
	"\x05value\x18\x02 \x01(\v2\x1b.tailbus.v1.ServiceManifestR\x05value:\x028\x01\"<\n" +
	"\x14RegisterNodeResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\".\n" +
	"\x13WatchPeerMapRequest\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\"\x84\x01\n" +
	"\rPeerMapUpdate\x12*\n" +
	"\x05peers\x18\x01 \x03(\v2\x14.tailbus.v1.PeerInfoR\x05peers\x12\x18\n" +
	"\aversion\x18\x02 \x01(\x03R\aversion\x12-\n" +
	"\x06relays\x18\x03 \x03(\v2\x15.tailbus.v1.RelayInfoR\x06relays\"W\n" +
	"\tRelayInfo\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12\x1d\n" +
	"\n" +
	"public_key\x18\x02 \x01(\fR\tpublicKey\x12\x12\n" +
	"\x04addr\x18\x03 \x01(\tR\x04addr\"\x94\x04\n" +
	"\bPeerInfo\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12\x1d\n" +
	"\n" +
	"public_key\x18\x02 \x01(\fR\tpublicKey\x12%\n" +
	"\x0eadvertise_addr\x18\x03 \x01(\tR\radvertiseAddr\x12\x18\n" +
	"\ahandles\x18\x04 \x03(\tR\ahandles\x12.\n" +
	"\x13last_heartbeat_unix\x18\x05 \x01(\x03R\x11lastHeartbeatUnix\x12a\n" +
	"\x13handle_descriptions\x18\x06 \x03(\v2,.tailbus.v1.PeerInfo.HandleDescriptionsEntryB\x02\x18\x01R\x12handleDescriptions\x12T\n" +
	"\x10handle_manifests\x18\a \x03(\v2).tailbus.v1.PeerInfo.HandleManifestsEntryR\x0fhandleManifests\x1aE\n" +
	"\x17HandleDescriptionsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1a_\n" +
	"\x14HandleManifestsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x121\n" +
	"\x05value\x18\x02 \x01(\v2\x1b.tailbus.v1.ServiceManifestR\x05value:\x028\x01\"-\n" +
	"\x13LookupHandleRequest\x12\x16\n" +
	"\x06handle\x18\x01 \x01(\tR\x06handle\"V\n" +
	"\x14LookupHandleResponse\x12(\n" +
	"\x04peer\x18\x01 \x01(\v2\x14.tailbus.v1.PeerInfoR\x04peer\x12\x14\n" +
	"\x05found\x18\x02 \x01(\bR\x05found\"\xb6\x03\n" +
	"\x10HeartbeatRequest\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12\x18\n" +
	"\ahandles\x18\x02 \x03(\tR\ahandles\x12i\n" +
	"\x13handle_descriptions\x18\x03 \x03(\v24.tailbus.v1.HeartbeatRequest.HandleDescriptionsEntryB\x02\x18\x01R\x12handleDescriptions\x12\\\n" +
	"\x10handle_manifests\x18\x04 \x03(\v21.tailbus.v1.HeartbeatRequest.HandleManifestsEntryR\x0fhandleManifests\x1aE\n" +
	"\x17HandleDescriptionsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1a_\n" +
	"\x14HandleManifestsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x121\n" +
	"\x05value\x18\x02 \x01(\v2\x1b.tailbus.v1.ServiceManifestR\x05value:\x028\x01\"#\n" +
	"\x11HeartbeatResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok2\xcf\x02\n" +
	"\x0fCoordinationAPI\x12Q\n" +
	"\fRegisterNode\x12\x1f.tailbus.v1.RegisterNodeRequest\x1a .tailbus.v1.RegisterNodeResponse\x12L\n" +
	"\fWatchPeerMap\x12\x1f.tailbus.v1.WatchPeerMapRequest\x1a\x19.tailbus.v1.PeerMapUpdate0\x01\x12Q\n" +
	"\fLookupHandle\x12\x1f.tailbus.v1.LookupHandleRequest\x1a .tailbus.v1.LookupHandleResponse\x12H\n" +
	"\tHeartbeat\x12\x1c.tailbus.v1.HeartbeatRequest\x1a\x1d.tailbus.v1.HeartbeatResponseB.Z,github.com/alexanderfrey/tailbus/api/coordpbb\x06proto3"

var (
	file_tailbus_v1_coord_proto_rawDescOnce sync.Once
	file_tailbus_v1_coord_proto_rawDescData []byte
)

func file_tailbus_v1_coord_proto_rawDescGZIP() []byte {
	file_tailbus_v1_coord_proto_rawDescOnce.Do(func() {
		file_tailbus_v1_coord_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_tailbus_v1_coord_proto_rawDesc), len(file_tailbus_v1_coord_proto_rawDesc)))
	})
	return file_tailbus_v1_coord_proto_rawDescData
}

var file_tailbus_v1_coord_proto_msgTypes = make([]protoimpl.MessageInfo, 16)
var file_tailbus_v1_coord_proto_goTypes = []any{
	(*RegisterNodeRequest)(nil),       // 0: tailbus.v1.RegisterNodeRequest
	(*RegisterNodeResponse)(nil),      // 1: tailbus.v1.RegisterNodeResponse
	(*WatchPeerMapRequest)(nil),       // 2: tailbus.v1.WatchPeerMapRequest
	(*PeerMapUpdate)(nil),             // 3: tailbus.v1.PeerMapUpdate
	(*RelayInfo)(nil),                 // 4: tailbus.v1.RelayInfo
	(*PeerInfo)(nil),                  // 5: tailbus.v1.PeerInfo
	(*LookupHandleRequest)(nil),       // 6: tailbus.v1.LookupHandleRequest
	(*LookupHandleResponse)(nil),      // 7: tailbus.v1.LookupHandleResponse
	(*HeartbeatRequest)(nil),          // 8: tailbus.v1.HeartbeatRequest
	(*HeartbeatResponse)(nil),         // 9: tailbus.v1.HeartbeatResponse
	nil,                               // 10: tailbus.v1.RegisterNodeRequest.HandleDescriptionsEntry
	nil,                               // 11: tailbus.v1.RegisterNodeRequest.HandleManifestsEntry
	nil,                               // 12: tailbus.v1.PeerInfo.HandleDescriptionsEntry
	nil,                               // 13: tailbus.v1.PeerInfo.HandleManifestsEntry
	nil,                               // 14: tailbus.v1.HeartbeatRequest.HandleDescriptionsEntry
	nil,                               // 15: tailbus.v1.HeartbeatRequest.HandleManifestsEntry
	(*messagepb.ServiceManifest)(nil), // 16: tailbus.v1.ServiceManifest
}
var file_tailbus_v1_coord_proto_depIdxs = []int32{
	10, // 0: tailbus.v1.RegisterNodeRequest.handle_descriptions:type_name -> tailbus.v1.RegisterNodeRequest.HandleDescriptionsEntry
	11, // 1: tailbus.v1.RegisterNodeRequest.handle_manifests:type_name -> tailbus.v1.RegisterNodeRequest.HandleManifestsEntry
	5,  // 2: tailbus.v1.PeerMapUpdate.peers:type_name -> tailbus.v1.PeerInfo
	4,  // 3: tailbus.v1.PeerMapUpdate.relays:type_name -> tailbus.v1.RelayInfo
	12, // 4: tailbus.v1.PeerInfo.handle_descriptions:type_name -> tailbus.v1.PeerInfo.HandleDescriptionsEntry
	13, // 5: tailbus.v1.PeerInfo.handle_manifests:type_name -> tailbus.v1.PeerInfo.HandleManifestsEntry
	5,  // 6: tailbus.v1.LookupHandleResponse.peer:type_name -> tailbus.v1.PeerInfo
	14, // 7: tailbus.v1.HeartbeatRequest.handle_descriptions:type_name -> tailbus.v1.HeartbeatRequest.HandleDescriptionsEntry
	15, // 8: tailbus.v1.HeartbeatRequest.handle_manifests:type_name -> tailbus.v1.HeartbeatRequest.HandleManifestsEntry
	16, // 9: tailbus.v1.RegisterNodeRequest.HandleManifestsEntry.value:type_name -> tailbus.v1.ServiceManifest
	16, // 10: tailbus.v1.PeerInfo.HandleManifestsEntry.value:type_name -> tailbus.v1.ServiceManifest
	16, // 11: tailbus.v1.HeartbeatRequest.HandleManifestsEntry.value:type_name -> tailbus.v1.ServiceManifest
	0,  // 12: tailbus.v1.CoordinationAPI.RegisterNode:input_type -> tailbus.v1.RegisterNodeRequest
	2,  // 13: tailbus.v1.CoordinationAPI.WatchPeerMap:input_type -> tailbus.v1.WatchPeerMapRequest
	6,  // 14: tailbus.v1.CoordinationAPI.LookupHandle:input_type -> tailbus.v1.LookupHandleRequest
	8,  // 15: tailbus.v1.CoordinationAPI.Heartbeat:input_type -> tailbus.v1.HeartbeatRequest
	1,  // 16: tailbus.v1.CoordinationAPI.RegisterNode:output_type -> tailbus.v1.RegisterNodeResponse
	3,  // 17: tailbus.v1.CoordinationAPI.WatchPeerMap:output_type -> tailbus.v1.PeerMapUpdate
	7,  // 18: tailbus.v1.CoordinationAPI.LookupHandle:output_type -> tailbus.v1.LookupHandleResponse
	9,  // 19: tailbus.v1.CoordinationAPI.Heartbeat:output_type -> tailbus.v1.HeartbeatResponse
	16, // [16:20] is the sub-list for method output_type
	12, // [12:16] is the sub-list for method input_type
	12, // [12:12] is the sub-list for extension type_name
	12, // [12:12] is the sub-list for extension extendee
	0,  // [0:12] is the sub-list for field type_name
}

func init() { file_tailbus_v1_coord_proto_init() }
func file_tailbus_v1_coord_proto_init() {
	if File_tailbus_v1_coord_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_tailbus_v1_coord_proto_rawDesc), len(file_tailbus_v1_coord_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   16,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_tailbus_v1_coord_proto_goTypes,
		DependencyIndexes: file_tailbus_v1_coord_proto_depIdxs,
		MessageInfos:      file_tailbus_v1_coord_proto_msgTypes,
	}.Build()
	File_tailbus_v1_coord_proto = out.File
	file_tailbus_v1_coord_proto_goTypes = nil
	file_tailbus_v1_coord_proto_depIdxs = nil
}
