// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.0
// source: tailbus/v1/agent.proto

package agentpb

import (
	messagepb "github.com/alexanderfrey/tailbus/api/messagepb"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TraceAction int32

const (
	TraceAction_TRACE_ACTION_UNSPECIFIED             TraceAction = 0
	TraceAction_TRACE_ACTION_MESSAGE_CREATED         TraceAction = 1
	TraceAction_TRACE_ACTION_ROUTED_LOCAL            TraceAction = 2
	TraceAction_TRACE_ACTION_ROUTED_REMOTE           TraceAction = 3
	TraceAction_TRACE_ACTION_SENT_TO_TRANSPORT       TraceAction = 4
	TraceAction_TRACE_ACTION_RECEIVED_FROM_TRANSPORT TraceAction = 5
	TraceAction_TRACE_ACTION_DELIVERED_TO_SUBSCRIBER TraceAction = 6
)

// Enum value maps for TraceAction.
var (
	TraceAction_name = map[int32]string{
		0: "TRACE_ACTION_UNSPECIFIED",
		1: "TRACE_ACTION_MESSAGE_CREATED",
		2: "TRACE_ACTION_ROUTED_LOCAL",
		3: "TRACE_ACTION_ROUTED_REMOTE",
		4: "TRACE_ACTION_SENT_TO_TRANSPORT",
		5: "TRACE_ACTION_RECEIVED_FROM_TRANSPORT",
		6: "TRACE_ACTION_DELIVERED_TO_SUBSCRIBER",
	}
	TraceAction_value = map[string]int32{
		"TRACE_ACTION_UNSPECIFIED":             0,
		"TRACE_ACTION_MESSAGE_CREATED":         1,
		"TRACE_ACTION_ROUTED_LOCAL":            2,
		"TRACE_ACTION_ROUTED_REMOTE":           3,
		"TRACE_ACTION_SENT_TO_TRANSPORT":       4,
		"TRACE_ACTION_RECEIVED_FROM_TRANSPORT": 5,
		"TRACE_ACTION_DELIVERED_TO_SUBSCRIBER": 6,
	}
)

func (x TraceAction) Enum() *TraceAction {
	p := new(TraceAction)
	*p = x
	return p
}

func (x TraceAction) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TraceAction) Descriptor() protoreflect.EnumDescriptor {
	return file_tailbus_v1_agent_proto_enumTypes[0].Descriptor()
}

func (TraceAction) Type() protoreflect.EnumType {
	return &file_tailbus_v1_agent_proto_enumTypes[0]
}

func (x TraceAction) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TraceAction.Descriptor instead.
func (TraceAction) EnumDescriptor() ([]byte, []int) {
	return file_tailbus_v1_agent_proto_rawDescGZIP(), []int{0}
}

type RegisterRequest struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	Handle string                 `protobuf:"bytes,1,opt,name=handle,proto3" json:"handle,omitempty"`
	// Deprecated: Marked as deprecated in tailbus/v1/agent.proto.
	Description   string                     `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	Manifest      *messagepb.ServiceManifest `protobuf:"bytes,3,opt,name=manifest,proto3" json:"manifest,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterRequest) Reset() {
	*x = RegisterRequest{}
	mi := &file_tailbus_v1_agent_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterRequest) ProtoMessage() {}

func (x *RegisterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tailbus_v1_agent_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterRequest.ProtoReflect.Descriptor instead.
func (*RegisterRequest) Descriptor() ([]byte, []int) {
	return file_tailbus_v1_agent_proto_rawDescGZIP(), []int{0}
}

func (x *RegisterRequest) GetHandle() string {
	if x != nil {
		return x.Handle
	}
	return ""
}

// Deprecated: Marked as deprecated in tailbus/v1/agent.proto.
func (x *RegisterRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *RegisterRequest) GetManifest() *messagepb.ServiceManifest {
	if x != nil {
		return x.Manifest
	}
	return nil
}

type RegisterResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterResponse) Reset() {
	*x = RegisterResponse{}
	mi := &file_tailbus_v1_agent_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterResponse) ProtoMessage() {}

func (x *RegisterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tailbus_v1_agent_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterResponse.ProtoReflect.Descriptor instead.
func (*RegisterResponse) Descriptor() ([]byte, []int) {
	return file_tailbus_v1_agent_proto_rawDescGZIP(), []int{1}
}

func (x *RegisterResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *RegisterResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type IntrospectHandleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Handle        string                 `protobuf:"bytes,1,opt,name=handle,proto3" json:"handle,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IntrospectHandleRequest) Reset() {
	*x = IntrospectHandleRequest{}
	mi := &file_tailbus_v1_agent_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IntrospectHandleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IntrospectHandleRequest) ProtoMessage() {}

func (x *IntrospectHandleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tailbus_v1_agent_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IntrospectHandleRequest.ProtoReflect.Descriptor instead.
func (*IntrospectHandleRequest) Descriptor() ([]byte, []int) {
	return file_tailbus_v1_agent_proto_rawDescGZIP(), []int{2}
}

func (x *IntrospectHandleRequest) GetHandle() string {
	if x != nil {
		return x.Handle
	}
	return ""
}

type IntrospectHandleResponse struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	Handle string                 `protobuf:"bytes,1,opt,name=handle,proto3" json:"handle,omitempty"`
	// Deprecated: Marked as deprecated in tailbus/v1/agent.proto.
	Description   string                     `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	Found         bool                       `protobuf:"varint,3,opt,name=found,proto3" json:"found,omitempty"`
	Manifest      *messagepb.ServiceManifest `protobuf:"bytes,4,opt,name=manifest,proto3" json:"manifest,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IntrospectHandleResponse) Reset() {
	*x = IntrospectHandleResponse{}
	mi := &file_tailbus_v1_agent_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IntrospectHandleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IntrospectHandleResponse) ProtoMessage() {}

func (x *IntrospectHandleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tailbus_v1_agent_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IntrospectHandleResponse.ProtoReflect.Descriptor instead.
func (*IntrospectHandleResponse) Descriptor() ([]byte, []int) {
	return file_tailbus_v1_agent_proto_rawDescGZIP(), []int{3}
}

func (x *IntrospectHandleResponse) GetHandle() string {
	if x != nil {
		return x.Handle
	}
	return ""
}

// Deprecated: Marked as deprecated in tailbus/v1/agent.proto.
func (x *IntrospectHandleResponse) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *IntrospectHandleResponse) GetFound() bool {
	if x != nil {
		return x.Found
	}
	return false
}

func (x *IntrospectHandleResponse) GetManifest() *messagepb.ServiceManifest {
	if x != nil {
		return x.Manifest
	}
	return nil
}

type ListHandlesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tags          []string               `protobuf:"bytes,1,rep,name=tags,proto3" json:"tags,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListHandlesRequest) Reset() {
	*x = ListHandlesRequest{}
	mi := &file_tailbus_v1_agent_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListHandlesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListHandlesRequest) ProtoMessage() {}

func (x *ListHandlesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tailbus_v1_agent_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListHandlesRequest.ProtoReflect.Descriptor instead.
func (*ListHandlesRequest) Descriptor() ([]byte, []int) {
	return file_tailbus_v1_agent_proto_rawDescGZIP(), []int{4}
}

func (x *ListHandlesRequest) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

type ListHandlesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Entries       []*HandleEntry         `protobuf:"bytes,1,rep,name=entries,proto3" json:"entries,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListHandlesResponse) Reset() {
	*x = ListHandlesResponse{}
	mi := &file_tailbus_v1_agent_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListHandlesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListHandlesResponse) ProtoMessage() {}

func (x *ListHandlesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tailbus_v1_agent_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListHandlesResponse.ProtoReflect.Descriptor instead.
func (*ListHandlesResponse) Descriptor() ([]byte, []int) {
	return file_tailbus_v1_agent_proto_rawDescGZIP(), []int{5}
}

func (x *ListHandlesResponse) GetEntries() []*HandleEntry {
	if x != nil {
		return x.Entries
	}
	return nil
}

type HandleEntry struct {
	state         protoimpl.MessageState     `protogen:"open.v1"`
	Handle        string                     `protobuf:"bytes,1,opt,name=handle,proto3" json:"handle,omitempty"`
	Manifest      *messagepb.ServiceManifest `protobuf:"bytes,2,opt,name=manifest,proto3" json:"manifest,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HandleEntry) Reset() {
	*x = HandleEntry{}
	mi := &file_tailbus_v1_agent_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HandleEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HandleEntry) ProtoMessage() {}

func (x *HandleEntry) ProtoReflect() protoreflect.Message {
	mi := &file_tailbus_v1_agent_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HandleEntry.ProtoReflect.Descriptor instead.
func (*HandleEntry) Descriptor() ([]byte, []int) {
	return file_tailbus_v1_agent_proto_rawDescGZIP(), []int{6}
}

func (x *HandleEntry) GetHandle() string {
	if x != nil {
		return x.Handle
	}
	return ""
}

func (x *HandleEntry) GetManifest() *messagepb.ServiceManifest {
	if x != nil {
		return x.Manifest
	}
	return nil
}

type OpenSessionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FromHandle    string                 `protobuf:"bytes,1,opt,name=from_handle,json=fromHandle,proto3" json:"from_handle,omitempty"`
	ToHandle      string                 `protobuf:"bytes,2,opt,name=to_handle,json=toHandle,proto3" json:"to_handle,omitempty"`
	Payload       []byte                 `protobuf:"bytes,3,opt,name=payload,proto3" json:"payload,omitempty"`
	ContentType   string                 `protobuf:"bytes,4,opt,name=content_type,json=contentType,proto3" json:"content_type,omitempty"`
	TraceId       string                 `protobuf:"bytes,5,opt,name=trace_id,json=traceId,proto3" json:"trace_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OpenSessionRequest) Reset() {
	*x = OpenSessionRequest{}
	mi := &file_tailbus_v1_agent_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OpenSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OpenSessionRequest) ProtoMessage() {}

func (x *OpenSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tailbus_v1_agent_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OpenSessionRequest.ProtoReflect.Descriptor instead.
func (*OpenSessionRequest) Descriptor() ([]byte, []int) {
	return file_tailbus_v1_agent_proto_rawDescGZIP(), []int{7}
}

func (x *OpenSessionRequest) GetFromHandle() string {
	if x != nil {
		return x.FromHandle
	}
	return ""
}

func (x *OpenSessionRequest) GetToHandle() string {
	if x != nil {
		return x.ToHandle
	}
	return ""
}

func (x *OpenSessionRequest) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *OpenSessionRequest) GetContentType() string {
	if x != nil {
		return x.ContentType
	}
	return ""
}

func (x *OpenSessionRequest) GetTraceId() string {
	if x != nil {
		return x.TraceId
	}
	return ""
}

type OpenSessionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	MessageId     string                 `protobuf:"bytes,2,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	TraceId       string                 `protobuf:"bytes,3,opt,name=trace_id,json=traceId,proto3" json:"trace_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OpenSessionResponse) Reset() {
	*x = OpenSessionResponse{}
	mi := &file_tailbus_v1_agent_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OpenSessionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OpenSessionResponse) ProtoMessage() {}

func (x *OpenSessionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tailbus_v1_agent_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OpenSessionResponse.ProtoReflect.Descriptor instead.
func (*OpenSessionResponse) Descriptor() ([]byte, []int) {
	return file_tailbus_v1_agent_proto_rawDescGZIP(), []int{8}
}

func (x *OpenSessionResponse) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *OpenSessionResponse) GetMessageId() string {
	if x != nil {
		return x.MessageId
	}
	return ""
}

func (x *OpenSessionResponse) GetTraceId() string {
	if x != nil {
		return x.TraceId
	}
	return ""
}

type SendMessageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	FromHandle    string                 `protobuf:"bytes,2,opt,name=from_handle,json=fromHandle,proto3" json:"from_handle,omitempty"`
	Payload       []byte                 `protobuf:"bytes,3,opt,name=payload,proto3" json:"payload,omitempty"`
	ContentType   string                 `protobuf:"bytes,4,opt,name=content_type,json=contentType,proto3" json:"content_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendMessageRequest) Reset() {
	*x = SendMessageRequest{}
	mi := &file_tailbus_v1_agent_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendMessageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendMessageRequest) ProtoMessage() {}

func (x *SendMessageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tailbus_v1_agent_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendMessageRequest.ProtoReflect.Descriptor instead.
func (*SendMessageRequest) Descriptor() ([]byte, []int) {
	return file_tailbus_v1_agent_proto_rawDescGZIP(), []int{9}
}

func (x *SendMessageRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *SendMessageRequest) GetFromHandle() string {
	if x != nil {
		return x.FromHandle
	}
	return ""
}

func (x *SendMessageRequest) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *SendMessageRequest) GetContentType() string {
	if x != nil {
		return x.ContentType
	}
	return ""
}

type SendMessageResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MessageId     string                 `protobuf:"bytes,1,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendMessageResponse) Reset() {
	*x = SendMessageResponse{}
	mi := &file_tailbus_v1_agent_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendMessageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendMessageResponse) ProtoMessage() {}

func (x *SendMessageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tailbus_v1_agent_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendMessageResponse.ProtoReflect.Descriptor instead.
func (*SendMessageResponse) Descriptor() ([]byte, []int) {
	return file_tailbus_v1_agent_proto_rawDescGZIP(), []int{10}
}

func (x *SendMessageResponse) GetMessageId() string {
	if x != nil {
		return x.MessageId
	}
	return ""
}

type SubscribeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Handle        string                 `protobuf:"bytes,1,opt,name=handle,proto3" json:"handle,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubscribeRequest) Reset() {
	*x = SubscribeRequest{}
	mi := &file_tailbus_v1_agent_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscribeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscribeRequest) ProtoMessage() {}

func (x *SubscribeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tailbus_v1_agent_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscribeRequest.ProtoReflect.Descriptor instead.
func (*SubscribeRequest) Descriptor() ([]byte, []int) {
	return file_tailbus_v1_agent_proto_rawDescGZIP(), []int{11}
}

func (x *SubscribeRequest) GetHandle() string {
	if x != nil {
		return x.Handle
	}
	return ""
}

type IncomingMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Envelope      *messagepb.Envelope    `protobuf:"bytes,1,opt,name=envelope,proto3" json:"envelope,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IncomingMessage) Reset() {
	*x = IncomingMessage{}
	mi := &file_tailbus_v1_agent_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IncomingMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IncomingMessage) ProtoMessage() {}

func (x *IncomingMessage) ProtoReflect() protoreflect.Message {
	mi := &file_tailbus_v1_agent_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IncomingMessage.ProtoReflect.Descriptor instead.
func (*IncomingMessage) Descriptor() ([]byte, []int) {
	return file_tailbus_v1_agent_proto_rawDescGZIP(), []int{12}
}

func (x *IncomingMessage) GetEnvelope() *messagepb.Envelope {
	if x != nil {
		return x.Envelope
	}
	return nil
}

type ResolveSessionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	FromHandle    string                 `protobuf:"bytes,2,opt,name=from_handle,json=fromHandle,proto3" json:"from_handle,omitempty"`
	Payload       []byte                 `protobuf:"bytes,3,opt,name=payload,proto3" json:"payload,omitempty"`
	ContentType   string                 `protobuf:"bytes,4,opt,name=content_type,json=contentType,proto3" json:"content_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResolveSessionRequest) Reset() {
	*x = ResolveSessionRequest{}
	mi := &file_tailbus_v1_agent_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResolveSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResolveSessionRequest) ProtoMessage() {}

func (x *ResolveSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tailbus_v1_agent_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResolveSessionRequest.ProtoReflect.Descriptor instead.
func (*ResolveSessionRequest) Descriptor() ([]byte, []int) {
	return file_tailbus_v1_agent_proto_rawDescGZIP(), []int{13}
}

func (x *ResolveSessionRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *ResolveSessionRequest) GetFromHandle() string {
	if x != nil {
		return x.FromHandle
	}
	return ""
}

func (x *ResolveSessionRequest) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *ResolveSessionRequest) GetContentType() string {
	if x != nil {
		return x.ContentType
	}
	return ""
}

type ResolveSessionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MessageId     string                 `protobuf:"bytes,1,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResolveSessionResponse) Reset() {
	*x = ResolveSessionResponse{}
	mi := &file_tailbus_v1_agent_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResolveSessionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResolveSessionResponse) ProtoMessage() {}

func (x *ResolveSessionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tailbus_v1_agent_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResolveSessionResponse.ProtoReflect.Descriptor instead.
func (*ResolveSessionResponse) Descriptor() ([]byte, []int) {
	return file_tailbus_v1_agent_proto_rawDescGZIP(), []int{14}
}

func (x *ResolveSessionResponse) GetMessageId() string {
	if x != nil {
		return x.MessageId
	}
	return ""
}

type ListSessionsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Handle        string                 `protobuf:"bytes,1,opt,name=handle,proto3" json:"handle,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSessionsRequest) Reset() {
	*x = ListSessionsRequest{}
	mi := &file_tailbus_v1_agent_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSessionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSessionsRequest) ProtoMessage() {}

func (x *ListSessionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tailbus_v1_agent_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSessionsRequest.ProtoReflect.Descriptor instead.
func (*ListSessionsRequest) Descriptor() ([]byte, []int) {
	return file_tailbus_v1_agent_proto_rawDescGZIP(), []int{15}
}

func (x *ListSessionsRequest) GetHandle() string {
	if x != nil {
		return x.Handle
	}
	return ""
}

type ListSessionsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sessions      []*SessionInfo         `protobuf:"bytes,1,rep,name=sessions,proto3" json:"sessions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSessionsResponse) Reset() {
	*x = ListSessionsResponse{}
	mi := &file_tailbus_v1_agent_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSessionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSessionsResponse) ProtoMessage() {}

func (x *ListSessionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tailbus_v1_agent_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSessionsResponse.ProtoReflect.Descriptor instead.
func (*ListSessionsResponse) Descriptor() ([]byte, []int) {
	return file_tailbus_v1_agent_proto_rawDescGZIP(), []int{16}
}

func (x *ListSessionsResponse) GetSessions() []*SessionInfo {
	if x != nil {
		return x.Sessions
	}
	return nil
}

type SessionInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	FromHandle    string                 `protobuf:"bytes,2,opt,name=from_handle,json=fromHandle,proto3" json:"from_handle,omitempty"`
	ToHandle      string                 `protobuf:"bytes,3,opt,name=to_handle,json=toHandle,proto3" json:"to_handle,omitempty"`
	State         string                 `protobuf:"bytes,4,opt,name=state,proto3" json:"state,omitempty"`
	CreatedAtUnix int64                  `protobuf:"varint,5,opt,name=created_at_unix,json=createdAtUnix,proto3" json:"created_at_unix,omitempty"`
	UpdatedAtUnix int64                  `protobuf:"varint,6,opt,name=updated_at_unix,json=updatedAtUnix,proto3" json:"updated_at_unix,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SessionInfo) Reset() {
	*x = SessionInfo{}
	mi := &file_tailbus_v1_agent_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SessionInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SessionInfo) ProtoMessage() {}

func (x *SessionInfo) ProtoReflect() protoreflect.Message {
	mi := &file_tailbus_v1_agent_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SessionInfo.ProtoReflect.Descriptor instead.
func (*SessionInfo) Descriptor() ([]byte, []int) {
	return file_tailbus_v1_agent_proto_rawDescGZIP(), []int{17}
}

func (x *SessionInfo) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *SessionInfo) GetFromHandle() string {
	if x != nil {
		return x.FromHandle
	}
	return ""
}

func (x *SessionInfo) GetToHandle() string {
	if x != nil {
		return x.ToHandle
	}
	return ""
}

func (x *SessionInfo) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *SessionInfo) GetCreatedAtUnix() int64 {
	if x != nil {
		return x.CreatedAtUnix
	}
	return 0
}

func (x *SessionInfo) GetUpdatedAtUnix() int64 {
	if x != nil {
		return x.UpdatedAtUnix
	}
	return 0
}

type GetNodeStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetNodeStatusRequest) Reset() {
	*x = GetNodeStatusRequest{}
	mi := &file_tailbus_v1_agent_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetNodeStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetNodeStatusRequest) ProtoMessage() {}

func (x *GetNodeStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tailbus_v1_agent_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetNodeStatusRequest.ProtoReflect.Descriptor instead.
func (*GetNodeStatusRequest) Descriptor() ([]byte, []int) {
	return file_tailbus_v1_agent_proto_rawDescGZIP(), []int{18}
}

type GetNodeStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	StartedAt     *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=started_at,json=startedAt,proto3" json:"started_at,omitempty"`
	Handles       []*HandleInfo          `protobuf:"bytes,3,rep,name=handles,proto3" json:"handles,omitempty"`
	Peers         []*PeerStatus          `protobuf:"bytes,4,rep,name=peers,proto3" json:"peers,omitempty"`
	Sessions      []*SessionInfo         `protobuf:"bytes,5,rep,name=sessions,proto3" json:"sessions,omitempty"`
	Counters      *Counters              `protobuf:"bytes,6,opt,name=counters,proto3" json:"counters,omitempty"`
	Relays        []*RelayStatus         `protobuf:"bytes,7,rep,name=relays,proto3" json:"relays,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetNodeStatusResponse) Reset() {
	*x = GetNodeStatusResponse{}
	mi := &file_tailbus_v1_agent_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetNodeStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetNodeStatusResponse) ProtoMessage() {}

func (x *GetNodeStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tailbus_v1_agent_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetNodeStatusResponse.ProtoReflect.Descriptor instead.
func (*GetNodeStatusResponse) Descriptor() ([]byte, []int) {
	return file_tailbus_v1_agent_proto_rawDescGZIP(), []int{19}
}

func (x *GetNodeStatusResponse) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *GetNodeStatusResponse) GetStartedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.StartedAt
	}
	return nil
}

func (x *GetNodeStatusResponse) GetHandles() []*HandleInfo {
	if x != nil {
		return x.Handles
	}
	return nil
}

func (x *GetNodeStatusResponse) GetPeers() []*PeerStatus {
	if x != nil {
		return x.Peers
	}
	return nil
}

func (x *GetNodeStatusResponse) GetSessions() []*SessionInfo {
	if x != nil {
		return x.Sessions
	}
	return nil
}

func (x *GetNodeStatusResponse) GetCounters() *Counters {
	if x != nil {
		return x.Counters
	}
	return nil
}

func (x *GetNodeStatusResponse) GetRelays() []*RelayStatus {
	if x != nil {
		return x.Relays
	}
	return nil
}

type RelayStatus struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	Addr          string                 `protobuf:"bytes,2,opt,name=addr,proto3" json:"addr,omitempty"`
	Connected     bool                   `protobuf:"varint,3,opt,name=connected,proto3" json:"connected,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RelayStatus) Reset() {
	*x = RelayStatus{}
	mi := &file_tailbus_v1_agent_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RelayStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RelayStatus) ProtoMessage() {}

func (x *RelayStatus) ProtoReflect() protoreflect.Message {
	mi := &file_tailbus_v1_agent_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RelayStatus.ProtoReflect.Descriptor instead.
func (*RelayStatus) Descriptor() ([]byte, []int) {
	return file_tailbus_v1_agent_proto_rawDescGZIP(), []int{20}
}

func (x *RelayStatus) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *RelayStatus) GetAddr() string {
	if x != nil {
		return x.Addr
	}
	return ""
}

func (x *RelayStatus) GetConnected() bool {
	if x != nil {
		return x.Connected
	}
	return false
}

type HandleInfo struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Name            string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	SubscriberCount int32                  `protobuf:"varint,2,opt,name=subscriber_count,json=subscriberCount,proto3" json:"subscriber_count,omitempty"`
	// Deprecated: Marked as deprecated in tailbus/v1/agent.proto.
	Description   string                     `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Manifest      *messagepb.ServiceManifest `protobuf:"bytes,4,opt,name=manifest,proto3" json:"manifest,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HandleInfo) Reset() {
	*x = HandleInfo{}
	mi := &file_tailbus_v1_agent_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HandleInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HandleInfo) ProtoMessage() {}

func (x *HandleInfo) ProtoReflect() protoreflect.Message {
	mi := &file_tailbus_v1_agent_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HandleInfo.ProtoReflect.Descriptor instead.
func (*HandleInfo) Descriptor() ([]byte, []int) {
	return file_tailbus_v1_agent_proto_rawDescGZIP(), []int{21}
}

func (x *HandleInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *HandleInfo) GetSubscriberCount() int32 {
	if x != nil {
		return x.SubscriberCount
	}
	return 0
}

// Deprecated: Marked as deprecated in tailbus/v1/agent.proto.
func (x *HandleInfo) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *HandleInfo) GetManifest() *messagepb.ServiceManifest {
	if x != nil {
		return x.Manifest
	}
	return nil
}

type PeerStatus struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	AdvertiseAddr string                 `protobuf:"bytes,2,opt,name=advertise_addr,json=advertiseAddr,proto3" json:"advertise_addr,omitempty"`
	Handles       []string               `protobuf:"bytes,3,rep,name=handles,proto3" json:"handles,omitempty"`
	Connected     bool                   `protobuf:"varint,4,opt,name=connected,proto3" json:"connected,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PeerStatus) Reset() {
	*x = PeerStatus{}
	mi := &file_tailbus_v1_agent_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PeerStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PeerStatus) ProtoMessage() {}

func (x *PeerStatus) ProtoReflect() protoreflect.Message {
	mi := &file_tailbus_v1_agent_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PeerStatus.ProtoReflect.Descriptor instead.
func (*PeerStatus) Descriptor() ([]byte, []int) {
	return file_tailbus_v1_agent_proto_rawDescGZIP(), []int{22}
}

func (x *PeerStatus) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *PeerStatus) GetAdvertiseAddr() string {
	if x != nil {
		return x.AdvertiseAddr
	}
	return ""
}

func (x *PeerStatus) GetHandles() []string {
	if x != nil {
		return x.Handles
	}
	return nil
}

func (x *PeerStatus) GetConnected() bool {
	if x != nil {
		return x.Connected
	}
	return false
}

type Counters struct {
	state                  protoimpl.MessageState `protogen:"open.v1"`
	MessagesRouted         int64                  `protobuf:"varint,1,opt,name=messages_routed,json=messagesRouted,proto3" json:"messages_routed,omitempty"`
	MessagesDeliveredLocal int64                  `protobuf:"varint,2,opt,name=messages_delivered_local,json=messagesDeliveredLocal,proto3" json:"messages_delivered_local,omitempty"`
	MessagesSentRemote     int64                  `protobuf:"varint,3,opt,name=messages_sent_remote,json=messagesSentRemote,proto3" json:"messages_sent_remote,omitempty"`
	MessagesReceivedRemote int64                  `protobuf:"varint,4,opt,name=messages_received_remote,json=messagesReceivedRemote,proto3" json:"messages_received_remote,omitempty"`
	SessionsOpened         int64                  `protobuf:"varint,5,opt,name=sessions_opened,json=sessionsOpened,proto3" json:"sessions_opened,omitempty"`
	SessionsResolved       int64                  `protobuf:"varint,6,opt,name=sessions_resolved,json=sessionsResolved,proto3" json:"sessions_resolved,omitempty"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *Counters) Reset() {
	*x = Counters{}
	mi := &file_tailbus_v1_agent_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Counters) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Counters) ProtoMessage() {}

func (x *Counters) ProtoReflect() protoreflect.Message {
	mi := &file_tailbus_v1_agent_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Counters.ProtoReflect.Descriptor instead.
func (*Counters) Descriptor() ([]byte, []int) {
	return file_tailbus_v1_agent_proto_rawDescGZIP(), []int{23}
}

func (x *Counters) GetMessagesRouted() int64 {
	if x != nil {
		return x.MessagesRouted
	}
	return 0
}

func (x *Counters) GetMessagesDeliveredLocal() int64 {
	if x != nil {
		return x.MessagesDeliveredLocal
	}
	return 0
}

func (x *Counters) GetMessagesSentRemote() int64 {
	if x != nil {
		return x.MessagesSentRemote
	}
	return 0
}

func (x *Counters) GetMessagesReceivedRemote() int64 {
	if x != nil {
		return x.MessagesReceivedRemote
	}
	return 0
}

func (x *Counters) GetSessionsOpened() int64 {
	if x != nil {
		return x.SessionsOpened
	}
	return 0
}

func (x *Counters) GetSessionsResolved() int64 {
	if x != nil {
		return x.SessionsResolved
	}
	return 0
}

type WatchActivityRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WatchActivityRequest) Reset() {
	*x = WatchActivityRequest{}
	mi := &file_tailbus_v1_agent_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WatchActivityRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WatchActivityRequest) ProtoMessage() {}

func (x *WatchActivityRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tailbus_v1_agent_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WatchActivityRequest.ProtoReflect.Descriptor instead.
func (*WatchActivityRequest) Descriptor() ([]byte, []int) {
	return file_tailbus_v1_agent_proto_rawDescGZIP(), []int{24}
}

type ActivityEvent struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	Timestamp *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	// Types that are valid to be assigned to Event:
	//
	//	*ActivityEvent_MessageRouted
	//	*ActivityEvent_SessionOpened
	//	*ActivityEvent_SessionResolved
	//	*ActivityEvent_HandleRegistered
	Event         isActivityEvent_Event `protobuf_oneof:"event"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ActivityEvent) Reset() {
	*x = ActivityEvent{}
	mi := &file_tailbus_v1_agent_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ActivityEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActivityEvent) ProtoMessage() {}

func (x *ActivityEvent) ProtoReflect() protoreflect.Message {
	mi := &file_tailbus_v1_agent_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActivityEvent.ProtoReflect.Descriptor instead.
func (*ActivityEvent) Descriptor() ([]byte, []int) {
	return file_tailbus_v1_agent_proto_rawDescGZIP(), []int{25}
}

func (x *ActivityEvent) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *ActivityEvent) GetEvent() isActivityEvent_Event {
	if x != nil {
		return x.Event
	}
	return nil
}

func (x *ActivityEvent) GetMessageRouted() *MessageRoutedEvent {
	if x != nil {
		if x, ok := x.Event.(*ActivityEvent_MessageRouted); ok {
			return x.MessageRouted
		}
	}
	return nil
}

func (x *ActivityEvent) GetSessionOpened() *SessionOpenedEvent {
	if x != nil {
		if x, ok := x.Event.(*ActivityEvent_SessionOpened); ok {
			return x.SessionOpened
		}
	}
	return nil
}

func (x *ActivityEvent) GetSessionResolved() *SessionResolvedEvent {
	if x != nil {
		if x, ok := x.Event.(*ActivityEvent_SessionResolved); ok {
			return x.SessionResolved
		}
	}
	return nil
}

func (x *ActivityEvent) GetHandleRegistered() *HandleRegisteredEvent {
	if x != nil {
		if x, ok := x.Event.(*ActivityEvent_HandleRegistered); ok {
			return x.HandleRegistered
		}
	}
	return nil
}

type isActivityEvent_Event interface {
	isActivityEvent_Event()
}

type ActivityEvent_MessageRouted struct {
	MessageRouted *MessageRoutedEvent `protobuf:"bytes,2,opt,name=message_routed,json=messageRouted,proto3,oneof"`
}

type ActivityEvent_SessionOpened struct {
	SessionOpened *SessionOpenedEvent `protobuf:"bytes,3,opt,name=session_opened,json=sessionOpened,proto3,oneof"`
}

type ActivityEvent_SessionResolved struct {
	SessionResolved *SessionResolvedEvent `protobuf:"bytes,4,opt,name=session_resolved,json=sessionResolved,proto3,oneof"`
}

type ActivityEvent_HandleRegistered struct {
	HandleRegistered *HandleRegisteredEvent `protobuf:"bytes,5,opt,name=handle_registered,json=handleRegistered,proto3,oneof"`
}

func (*ActivityEvent_MessageRouted) isActivityEvent_Event() {}

func (*ActivityEvent_SessionOpened) isActivityEvent_Event() {}

func (*ActivityEvent_SessionResolved) isActivityEvent_Event() {}

func (*ActivityEvent_HandleRegistered) isActivityEvent_Event() {}

type MessageRoutedEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	FromHandle    string                 `protobuf:"bytes,2,opt,name=from_handle,json=fromHandle,proto3" json:"from_handle,omitempty"`
	ToHandle      string                 `protobuf:"bytes,3,opt,name=to_handle,json=toHandle,proto3" json:"to_handle,omitempty"`
	Remote        bool                   `protobuf:"varint,4,opt,name=remote,proto3" json:"remote,omitempty"`
	TraceId       string                 `protobuf:"bytes,5,opt,name=trace_id,json=traceId,proto3" json:"trace_id,omitempty"`
	MessageId     string                 `protobuf:"bytes,6,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MessageRoutedEvent) Reset() {
	*x = MessageRoutedEvent{}
	mi := &file_tailbus_v1_agent_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MessageRoutedEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageRoutedEvent) ProtoMessage() {}

func (x *MessageRoutedEvent) ProtoReflect() protoreflect.Message {
	mi := &file_tailbus_v1_agent_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageRoutedEvent.ProtoReflect.Descriptor instead.
func (*MessageRoutedEvent) Descriptor() ([]byte, []int) {
	return file_tailbus_v1_agent_proto_rawDescGZIP(), []int{26}
}

func (x *MessageRoutedEvent) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *MessageRoutedEvent) GetFromHandle() string {
	if x != nil {
		return x.FromHandle
	}
	return ""
}

func (x *MessageRoutedEvent) GetToHandle() string {
	if x != nil {
		return x.ToHandle
	}
	return ""
}

func (x *MessageRoutedEvent) GetRemote() bool {
	if x != nil {
		return x.Remote
	}
	return false
}

func (x *MessageRoutedEvent) GetTraceId() string {
	if x != nil {
		return x.TraceId
	}
	return ""
}

func (x *MessageRoutedEvent) GetMessageId() string {
	if x != nil {
		return x.MessageId
	}
	return ""
}

type SessionOpenedEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	FromHandle    string                 `protobuf:"bytes,2,opt,name=from_handle,json=fromHandle,proto3" json:"from_handle,omitempty"`
	ToHandle      string                 `protobuf:"bytes,3,opt,name=to_handle,json=toHandle,proto3" json:"to_handle,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SessionOpenedEvent) Reset() {
	*x = SessionOpenedEvent{}
	mi := &file_tailbus_v1_agent_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SessionOpenedEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SessionOpenedEvent) ProtoMessage() {}

func (x *SessionOpenedEvent) ProtoReflect() protoreflect.Message {
	mi := &file_tailbus_v1_agent_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SessionOpenedEvent.ProtoReflect.Descriptor instead.
func (*SessionOpenedEvent) Descriptor() ([]byte, []int) {
	return file_tailbus_v1_agent_proto_rawDescGZIP(), []int{27}
}

func (x *SessionOpenedEvent) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *SessionOpenedEvent) GetFromHandle() string {
	if x != nil {
		return x.FromHandle
	}
	return ""
}

func (x *SessionOpenedEvent) GetToHandle() string {
	if x != nil {
		return x.ToHandle
	}
	return ""
}

type SessionResolvedEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	FromHandle    string                 `protobuf:"bytes,2,opt,name=from_handle,json=fromHandle,proto3" json:"from_handle,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SessionResolvedEvent) Reset() {
	*x = SessionResolvedEvent{}
	mi := &file_tailbus_v1_agent_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SessionResolvedEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SessionResolvedEvent) ProtoMessage() {}

func (x *SessionResolvedEvent) ProtoReflect() protoreflect.Message {
	mi := &file_tailbus_v1_agent_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SessionResolvedEvent.ProtoReflect.Descriptor instead.
func (*SessionResolvedEvent) Descriptor() ([]byte, []int) {
	return file_tailbus_v1_agent_proto_rawDescGZIP(), []int{28}
}

func (x *SessionResolvedEvent) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *SessionResolvedEvent) GetFromHandle() string {
	if x != nil {
		return x.FromHandle
	}
	return ""
}

type HandleRegisteredEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Handle        string                 `protobuf:"bytes,1,opt,name=handle,proto3" json:"handle,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HandleRegisteredEvent) Reset() {
	*x = HandleRegisteredEvent{}
	mi := &file_tailbus_v1_agent_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HandleRegisteredEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HandleRegisteredEvent) ProtoMessage() {}

func (x *HandleRegisteredEvent) ProtoReflect() protoreflect.Message {
	mi := &file_tailbus_v1_agent_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HandleRegisteredEvent.ProtoReflect.Descriptor instead.
func (*HandleRegisteredEvent) Descriptor() ([]byte, []int) {
	return file_tailbus_v1_agent_proto_rawDescGZIP(), []int{29}
}

func (x *HandleRegisteredEvent) GetHandle() string {
	if x != nil {
		return x.Handle
	}
	return ""
}

type TraceSpan struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TraceId       string                 `protobuf:"bytes,1,opt,name=trace_id,json=traceId,proto3" json:"trace_id,omitempty"`
	MessageId     string                 `protobuf:"bytes,2,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	NodeId        string                 `protobuf:"bytes,3,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	Action        TraceAction            `protobuf:"varint,4,opt,name=action,proto3,enum=tailbus.v1.TraceAction" json:"action,omitempty"`
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Metadata      map[string]string      `protobuf:"bytes,6,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TraceSpan) Reset() {
	*x = TraceSpan{}
	mi := &file_tailbus_v1_agent_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TraceSpan) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TraceSpan) ProtoMessage() {}

func (x *TraceSpan) ProtoReflect() protoreflect.Message {
	mi := &file_tailbus_v1_agent_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TraceSpan.ProtoReflect.Descriptor instead.
func (*TraceSpan) Descriptor() ([]byte, []int) {
	return file_tailbus_v1_agent_proto_rawDescGZIP(), []int{30}
}

func (x *TraceSpan) GetTraceId() string {
	if x != nil {
		return x.TraceId
	}
	return ""
}

func (x *TraceSpan) GetMessageId() string {
	if x != nil {
		return x.MessageId
	}
	return ""
}

func (x *TraceSpan) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *TraceSpan) GetAction() TraceAction {
	if x != nil {
		return x.Action
	}
	return TraceAction_TRACE_ACTION_UNSPECIFIED
}

func (x *TraceSpan) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *TraceSpan) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type GetTraceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TraceId       string                 `protobuf:"bytes,1,opt,name=trace_id,json=traceId,proto3" json:"trace_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTraceRequest) Reset() {
	*x = GetTraceRequest{}
	mi := &file_tailbus_v1_agent_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTraceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTraceRequest) ProtoMessage() {}

func (x *GetTraceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tailbus_v1_agent_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTraceRequest.ProtoReflect.Descriptor instead.
func (*GetTraceRequest) Descriptor() ([]byte, []int) {
	return file_tailbus_v1_agent_proto_rawDescGZIP(), []int{31}
}

func (x *GetTraceRequest) GetTraceId() string {
	if x != nil {
		return x.TraceId
	}
	return ""
}

type GetTraceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Spans         []*TraceSpan           `protobuf:"bytes,1,rep,name=spans,proto3" json:"spans,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTraceResponse) Reset() {
	*x = GetTraceResponse{}
	mi := &file_tailbus_v1_agent_proto_msgTypes[32]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTraceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTraceResponse) ProtoMessage() {}

func (x *GetTraceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tailbus_v1_agent_proto_msgTypes[32]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTraceResponse.ProtoReflect.Descriptor instead.
func (*GetTraceResponse) Descriptor() ([]byte, []int) {
	return file_tailbus_v1_agent_proto_rawDescGZIP(), []int{32}
}

func (x *GetTraceResponse) GetSpans() []*TraceSpan {
	if x != nil {
		return x.Spans
	}
	return nil
}

var File_tailbus_v1_agent_proto protoreflect.FileDescriptor

const file_tailbus_v1_agent_proto_rawDesc = "" +
	"\n" +
	"\x16tailbus/v1/agent.proto\x12\n" +
	"tailbus.v1\x1a\x19tailbus/v1/messages.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\x88\x01\n" +
	"\x0fRegisterRequest\x12\x16\n" +
	"\x06handle\x18\x01 \x01(\tR\x06handle\x12$\n" +
	"\vdescription\x18\x02 \x01(\tB\x02\x18\x01R\vdescription\x127\n" +
	"\bmanifest\x18\x03 \x01(\v2\x1b.tailbus.v1.ServiceManifestR\bmanifest\"8\n" +
	"\x10RegisterResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"1\n" +
	"\x17IntrospectHandleRequest\x12\x16\n" +
	"\x06handle\x18\x01 \x01(\tR\x06handle\"\xa7\x01\n" +
	"\x18IntrospectHandleResponse\x12\x16\n" +
	"\x06handle\x18\x01 \x01(\tR\x06handle\x12$\n" +
	"\vdescription\x18\x02 \x01(\tB\x02\x18\x01R\vdescription\x12\x14\n" +
	"\x05found\x18\x03 \x01(\bR\x05found\x127\n" +
	"\bmanifest\x18\x04 \x01(\v2\x1b.tailbus.v1.ServiceManifestR\bmanifest\"(\n" +
	"\x12ListHandlesRequest\x12\x12\n" +
	"\x04tags\x18\x01 \x03(\tR\x04tags\"H\n" +
	"\x13ListHandlesResponse\x121\n" +
	"\aentries\x18\x01 \x03(\v2\x17.tailbus.v1.HandleEntryR\aentries\"^\n" +
	"\vHandleEntry\x12\x16\n" +
	"\x06handle\x18\x01 \x01(\tR\x06handle\x127\n" +
	"\bmanifest\x18\x02 \x01(\v2\x1b.tailbus.v1.ServiceManifestR\bmanifest\"\xaa\x01\n" +
	"\x12OpenSessionRequest\x12\x1f\n" +
	"\vfrom_handle\x18\x01 \x01(\tR\n" +
	"fromHandle\x12\x1b\n" +
	"\tto_handle\x18\x02 \x01(\tR\btoHandle\x12\x18\n" +
	"\apayload\x18\x03 \x01(\fR\apayload\x12!\n" +
	"\fcontent_type\x18\x04 \x01(\tR\vcontentType\x12\x19\n" +
	"\btrace_id\x18\x05 \x01(\tR\atraceId\"n\n" +
	"\x13OpenSessionResponse\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x1d\n" +
	"\n" +
	"message_id\x18\x02 \x01(\tR\tmessageId\x12\x19\n" +
	"\btrace_id\x18\x03 \x01(\tR\atraceId\"\x91\x01\n" +
	"\x12SendMessageRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x1f\n" +
	"\vfrom_handle\x18\x02 \x01(\tR\n" +
	"fromHandle\x12\x18\n" +
	"\apayload\x18\x03 \x01(\fR\apayload\x12!\n" +
	"\fcontent_type\x18\x04 \x01(\tR\vcontentType\"4\n" +
	"\x13SendMessageResponse\x12\x1d\n" +
	"\n" +
	"message_id\x18\x01 \x01(\tR\tmessageId\"*\n" +
	"\x10SubscribeRequest\x12\x16\n" +
	"\x06handle\x18\x01 \x01(\tR\x06handle\"C\n" +
	"\x0fIncomingMessage\x120\n" +
	"\benvelope\x18\x01 \x01(\v2\x14.tailbus.v1.EnvelopeR\benvelope\"\x94\x01\n" +
	"\x15ResolveSessionRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x1f\n" +
	"\vfrom_handle\x18\x02 \x01(\tR\n" +
	"fromHandle\x12\x18\n" +
	"\apayload\x18\x03 \x01(\fR\apayload\x12!\n" +
	"\fcontent_type\x18\x04 \x01(\tR\vcontentType\"7\n" +
	"\x16ResolveSessionResponse\x12\x1d\n" +
	"\n" +
	"message_id\x18\x01 \x01(\tR\tmessageId\"-\n" +
	"\x13ListSessionsRequest\x12\x16\n" +
	"\x06handle\x18\x01 \x01(\tR\x06handle\"K\n" +
	"\x14ListSessionsResponse\x123\n" +
	"\bsessions\x18\x01 \x03(\v2\x17.tailbus.v1.SessionInfoR\bsessions\"\xd0\x01\n" +
	"\vSessionInfo\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x1f\n" +
	"\vfrom_handle\x18\x02 \x01(\tR\n" +
	"fromHandle\x12\x1b\n" +
	"\tto_handle\x18\x03 \x01(\tR\btoHandle\x12\x14\n" +
	"\x05state\x18\x04 \x01(\tR\x05state\x12&\n" +
	"\x0fcreated_at_unix\x18\x05 \x01(\x03R\rcreatedAtUnix\x12&\n" +
	"\x0fupdated_at_unix\x18\x06 \x01(\x03R\rupdatedAtUnix\"\x16\n" +
	"\x14GetNodeStatusRequest\"\xe3\x02\n" +
	"\x15GetNodeStatusResponse\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x129\n" +
	"\n" +
	"started_at\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\tstartedAt\x120\n" +
	"\ahandles\x18\x03 \x03(\v2\x16.tailbus.v1.HandleInfoR\ahandles\x12,\n" +
	"\x05peers\x18\x04 \x03(\v2\x16.tailbus.v1.PeerStatusR\x05peers\x123\n" +
	"\bsessions\x18\x05 \x03(\v2\x17.tailbus.v1.SessionInfoR\bsessions\x120\n" +
	"\bcounters\x18\x06 \x01(\v2\x14.tailbus.v1.CountersR\bcounters\x12/\n" +
	"\x06relays\x18\a \x03(\v2\x17.tailbus.v1.RelayStatusR\x06relays\"X\n" +
	"\vRelayStatus\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12\x12\n" +
	"\x04addr\x18\x02 \x01(\tR\x04addr\x12\x1c\n" +
	"\tconnected\x18\x03 \x01(\bR\tconnected\"\xaa\x01\n" +
	"\n" +
	"HandleInfo\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12)\n" +
	"\x10subscriber_count\x18\x02 \x01(\x05R\x0fsubscriberCount\x12$\n" +
	"\vdescription\x18\x03 \x01(\tB\x02\x18\x01R\vdescription\x127\n" +
	"\bmanifest\x18\x04 \x01(\v2\x1b.tailbus.v1.ServiceManifestR\bmanifest\"\x84\x01\n" +
	"\n" +
	"PeerStatus\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12%\n" +
	"\x0eadvertise_addr\x18\x02 \x01(\tR\radvertiseAddr\x12\x18\n" +
	"\ahandles\x18\x03 \x03(\tR\ahandles\x12\x1c\n" +
	"\tconnected\x18\x04 \x01(\bR\tconnected\"\xaf\x02\n" +
	"\bCounters\x12'\n" +
	"\x0fmessages_routed\x18\x01 \x01(\x03R\x0emessagesRouted\x128\n" +
	"\x18messages_delivered_local\x18\x02 \x01(\x03R\x16messagesDeliveredLocal\x120\n" +
	"\x14messages_sent_remote\x18\x03 \x01(\x03R\x12messagesSentRemote\x128\n" +
	"\x18messages_received_remote\x18\x04 \x01(\x03R\x16messagesReceivedRemote\x12'\n" +
	"\x0fsessions_opened\x18\x05 \x01(\x03R\x0esessionsOpened\x12+\n" +
	"\x11sessions_resolved\x18\x06 \x01(\x03R\x10sessionsResolved\"\x16\n" +
	"\x14WatchActivityRequest\"\x85\x03\n" +
	"\rActivityEvent\x128\n" +
	"\ttimestamp\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x12G\n" +
	"\x0emessage_routed\x18\x02 \x01(\v2\x1e.tailbus.v1.MessageRoutedEventH\x00R\rmessageRouted\x12G\n" +
	"\x0esession_opened\x18\x03 \x01(\v2\x1e.tailbus.v1.SessionOpenedEventH\x00R\rsessionOpened\x12M\n" +
	"\x10session_resolved\x18\x04 \x01(\v2 .tailbus.v1.SessionResolvedEventH\x00R\x0fsessionResolved\x12P\n" +
	"\x11handle_registered\x18\x05 \x01(\v2!.tailbus.v1.HandleRegisteredEventH\x00R\x10handleRegisteredB\a\n" +
	"\x05event\"\xc3\x01\n" +
	"\x12MessageRoutedEvent\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x1f\n" +
	"\vfrom_handle\x18\x02 \x01(\tR\n" +
	"fromHandle\x12\x1b\n" +
	"\tto_handle\x18\x03 \x01(\tR\btoHandle\x12\x16\n" +
	"\x06remote\x18\x04 \x01(\bR\x06remote\x12\x19\n" +
	"\btrace_id\x18\x05 \x01(\tR\atraceId\x12\x1d\n" +
	"\n" +
	"message_id\x18\x06 \x01(\tR\tmessageId\"q\n" +
	"\x12SessionOpenedEvent\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x1f\n" +
	"\vfrom_handle\x18\x02 \x01(\tR\n" +
	"fromHandle\x12\x1b\n" +
	"\tto_handle\x18\x03 \x01(\tR\btoHandle\"V\n" +
	"\x14SessionResolvedEvent\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x1f\n" +
	"\vfrom_handle\x18\x02 \x01(\tR\n" +
	"fromHandle\"/\n" +
	"\x15HandleRegisteredEvent\x12\x16\n" +
	"\x06handle\x18\x01 \x01(\tR\x06handle\"\xc7\x02\n" +
	"\tTraceSpan\x12\x19\n" +
	"\btrace_id\x18\x01 \x01(\tR\atraceId\x12\x1d\n" +
	"\n" +
	"message_id\x18\x02 \x01(\tR\tmessageId\x12\x17\n" +
	"\anode_id\x18\x03 \x01(\tR\x06nodeId\x12/\n" +
	"\x06action\x18\x04 \x01(\x0e2\x17.tailbus.v1.TraceActionR\x06action\x128\n" +
	"\ttimestamp\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x12?\n" +
	"\bmetadata\x18\x06 \x03(\v2#.tailbus.v1.TraceSpan.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\",\n" +
	"\x0fGetTraceRequest\x12\x19\n" +
	"\btrace_id\x18\x01 \x01(\tR\atraceId\"?\n" +
	"\x10GetTraceResponse\x12+\n" +
	"\x05spans\x18\x01 \x03(\v2\x15.tailbus.v1.TraceSpanR\x05spans*\x84\x02\n" +
	"\vTraceAction\x12\x1c\n" +
	"\x18TRACE_ACTION_UNSPECIFIED\x10\x00\x12 \n" +
	"\x1cTRACE_ACTION_MESSAGE_CREATED\x10\x01\x12\x1d\n" +
	"\x19TRACE_ACTION_ROUTED_LOCAL\x10\x02\x12\x1e\n" +
	"\x1aTRACE_ACTION_ROUTED_REMOTE\x10\x03\x12\"\n" +
	"\x1eTRACE_ACTION_SENT_TO_TRANSPORT\x10\x04\x12(\n" +
	"$TRACE_ACTION_RECEIVED_FROM_TRANSPORT\x10\x05\x12(\n" +
	"$TRACE_ACTION_DELIVERED_TO_SUBSCRIBER\x10\x062\x83\a\n" +
	"\bAgentAPI\x12E\n" +
	"\bRegister\x12\x1b.tailbus.v1.RegisterRequest\x1a\x1c.tailbus.v1.RegisterResponse\x12]\n" +
	"\x10IntrospectHandle\x12#.tailbus.v1.IntrospectHandleRequest\x1a$.tailbus.v1.IntrospectHandleResponse\x12N\n" +
	"\vListHandles\x12\x1e.tailbus.v1.ListHandlesRequest\x1a\x1f.tailbus.v1.ListHandlesResponse\x12N\n" +
	"\vOpenSession\x12\x1e.tailbus.v1.OpenSessionRequest\x1a\x1f.tailbus.v1.OpenSessionResponse\x12N\n" +
	"\vSendMessage\x12\x1e.tailbus.v1.SendMessageRequest\x1a\x1f.tailbus.v1.SendMessageResponse\x12H\n" +
	"\tSubscribe\x12\x1c.tailbus.v1.SubscribeRequest\x1a\x1b.tailbus.v1.IncomingMessage0\x01\x12W\n" +
	"\x0eResolveSession\x12!.tailbus.v1.ResolveSessionRequest\x1a\".tailbus.v1.ResolveSessionResponse\x12Q\n" +
	"\fListSessions\x12\x1f.tailbus.v1.ListSessionsRequest\x1a .tailbus.v1.ListSessionsResponse\x12T\n" +
	"\rGetNodeStatus\x12 .tailbus.v1.GetNodeStatusRequest\x1a!.tailbus.v1.GetNodeStatusResponse\x12N\n" +
	"\rWatchActivity\x12 .tailbus.v1.WatchActivityRequest\x1a\x19.tailbus.v1.ActivityEvent0\x01\x12E\n" +
	"\bGetTrace\x12\x1b.tailbus.v1.GetTraceRequest\x1a\x1c.tailbus.v1.GetTraceResponseB.Z,github.com/alexanderfrey/tailbus/api/agentpbb\x06proto3"

var (
	file_tailbus_v1_agent_proto_rawDescOnce sync.Once
	file_tailbus_v1_agent_proto_rawDescData []byte
)

func file_tailbus_v1_agent_proto_rawDescGZIP() []byte {
	file_tailbus_v1_agent_proto_rawDescOnce.Do(func() {
		file_tailbus_v1_agent_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_tailbus_v1_agent_proto_rawDesc), len(file_tailbus_v1_agent_proto_rawDesc)))
	})
	return file_tailbus_v1_agent_proto_rawDescData
}

var file_tailbus_v1_agent_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_tailbus_v1_agent_proto_msgTypes = make([]protoimpl.MessageInfo, 34)
var file_tailbus_v1_agent_proto_goTypes = []any{
	(TraceAction)(0),                  // 0: tailbus.v1.TraceAction
	(*RegisterRequest)(nil),           // 1: tailbus.v1.RegisterRequest
	(*RegisterResponse)(nil),          // 2: tailbus.v1.RegisterResponse
	(*IntrospectHandleRequest)(nil),   // 3: tailbus.v1.IntrospectHandleRequest
	(*IntrospectHandleResponse)(nil),  // 4: tailbus.v1.IntrospectHandleResponse
	(*ListHandlesRequest)(nil),        // 5: tailbus.v1.ListHandlesRequest
	(*ListHandlesResponse)(nil),       // 6: tailbus.v1.ListHandlesResponse
	(*HandleEntry)(nil),               // 7: tailbus.v1.HandleEntry
	(*OpenSessionRequest)(nil),        // 8: tailbus.v1.OpenSessionRequest
	(*OpenSessionResponse)(nil),       // 9: tailbus.v1.OpenSessionResponse
	(*SendMessageRequest)(nil),        // 10: tailbus.v1.SendMessageRequest
	(*SendMessageResponse)(nil),       // 11: tailbus.v1.SendMessageResponse
	(*SubscribeRequest)(nil),          // 12: tailbus.v1.SubscribeRequest
	(*IncomingMessage)(nil),           // 13: tailbus.v1.IncomingMessage
	(*ResolveSessionRequest)(nil),     // 14: tailbus.v1.ResolveSessionRequest
	(*ResolveSessionResponse)(nil),    // 15: tailbus.v1.ResolveSessionResponse
	(*ListSessionsRequest)(nil),       // 16: tailbus.v1.ListSessionsRequest
	(*ListSessionsResponse)(nil),      // 17: tailbus.v1.ListSessionsResponse
	(*SessionInfo)(nil),               // 18: tailbus.v1.SessionInfo
	(*GetNodeStatusRequest)(nil),      // 19: tailbus.v1.GetNodeStatusRequest
	(*GetNodeStatusResponse)(nil),     // 20: tailbus.v1.GetNodeStatusResponse
	(*RelayStatus)(nil),               // 21: tailbus.v1.RelayStatus
	(*HandleInfo)(nil),                // 22: tailbus.v1.HandleInfo
	(*PeerStatus)(nil),                // 23: tailbus.v1.PeerStatus
	(*Counters)(nil),                  // 24: tailbus.v1.Counters
	(*WatchActivityRequest)(nil),      // 25: tailbus.v1.WatchActivityRequest
	(*ActivityEvent)(nil),             // 26: tailbus.v1.ActivityEvent
	(*MessageRoutedEvent)(nil),        // 27: tailbus.v1.MessageRoutedEvent
	(*SessionOpenedEvent)(nil),        // 28: tailbus.v1.SessionOpenedEvent
	(*SessionResolvedEvent)(nil),      // 29: tailbus.v1.SessionResolvedEvent
	(*HandleRegisteredEvent)(nil),     // 30: tailbus.v1.HandleRegisteredEvent
	(*TraceSpan)(nil),                 // 31: tailbus.v1.TraceSpan
	(*GetTraceRequest)(nil),           // 32: tailbus.v1.GetTraceRequest
	(*GetTraceResponse)(nil),          // 33: tailbus.v1.GetTraceResponse
	nil,                               // 34: tailbus.v1.TraceSpan.MetadataEntry
	(*messagepb.ServiceManifest)(nil), // 35: tailbus.v1.ServiceManifest
	(*messagepb.Envelope)(nil),        // 36: tailbus.v1.Envelope
	(*timestamppb.Timestamp)(nil),     // 37: google.protobuf.Timestamp
}
var file_tailbus_v1_agent_proto_depIdxs = []int32{
	35, // 0: tailbus.v1.RegisterRequest.manifest:type_name -> tailbus.v1.ServiceManifest
	35, // 1: tailbus.v1.IntrospectHandleResponse.manifest:type_name -> tailbus.v1.ServiceManifest
	7,  // 2: tailbus.v1.ListHandlesResponse.entries:type_name -> tailbus.v1.HandleEntry
	35, // 3: tailbus.v1.HandleEntry.manifest:type_name -> tailbus.v1.ServiceManifest
	36, // 4: tailbus.v1.IncomingMessage.envelope:type_name -> tailbus.v1.Envelope
	18, // 5: tailbus.v1.ListSessionsResponse.sessions:type_name -> tailbus.v1.SessionInfo
	37, // 6: tailbus.v1.GetNodeStatusResponse.started_at:type_name -> google.protobuf.Timestamp
	22, // 7: tailbus.v1.GetNodeStatusResponse.handles:type_name -> tailbus.v1.HandleInfo
	23, // 8: tailbus.v1.GetNodeStatusResponse.peers:type_name -> tailbus.v1.PeerStatus
	18, // 9: tailbus.v1.GetNodeStatusResponse.sessions:type_name -> tailbus.v1.SessionInfo
	24, // 10: tailbus.v1.GetNodeStatusResponse.counters:type_name -> tailbus.v1.Counters
	21, // 11: tailbus.v1.GetNodeStatusResponse.relays:type_name -> tailbus.v1.RelayStatus
	35, // 12: tailbus.v1.HandleInfo.manifest:type_name -> tailbus.v1.ServiceManifest
	37, // 13: tailbus.v1.ActivityEvent.timestamp:type_name -> google.protobuf.Timestamp
	27, // 14: tailbus.v1.ActivityEvent.message_routed:type_name -> tailbus.v1.MessageRoutedEvent
	28, // 15: tailbus.v1.ActivityEvent.session_opened:type_name -> tailbus.v1.SessionOpenedEvent
	29, // 16: tailbus.v1.ActivityEvent.session_resolved:type_name -> tailbus.v1.SessionResolvedEvent
	30, // 17: tailbus.v1.ActivityEvent.handle_registered:type_name -> tailbus.v1.HandleRegisteredEvent
	0,  // 18: tailbus.v1.TraceSpan.action:type_name -> tailbus.v1.TraceAction
	37, // 19: tailbus.v1.TraceSpan.timestamp:type_name -> google.protobuf.Timestamp
	34, // 20: tailbus.v1.TraceSpan.metadata:type_name -> tailbus.v1.TraceSpan.MetadataEntry
	31, // 21: tailbus.v1.GetTraceResponse.spans:type_name -> tailbus.v1.TraceSpan
	1,  // 22: tailbus.v1.AgentAPI.Register:input_type -> tailbus.v1.RegisterRequest
	3,  // 23: tailbus.v1.AgentAPI.IntrospectHandle:input_type -> tailbus.v1.IntrospectHandleRequest
	5,  // 24: tailbus.v1.AgentAPI.ListHandles:input_type -> tailbus.v1.ListHandlesRequest
	8,  // 25: tailbus.v1.AgentAPI.OpenSession:input_type -> tailbus.v1.OpenSessionRequest
	10, // 26: tailbus.v1.AgentAPI.SendMessage:input_type -> tailbus.v1.SendMessageRequest
	12, // 27: tailbus.v1.AgentAPI.Subscribe:input_type -> tailbus.v1.SubscribeRequest
	14, // 28: tailbus.v1.AgentAPI.ResolveSession:input_type -> tailbus.v1.ResolveSessionRequest
	16, // 29: tailbus.v1.AgentAPI.ListSessions:input_type -> tailbus.v1.ListSessionsRequest
	19, // 30: tailbus.v1.AgentAPI.GetNodeStatus:input_type -> tailbus.v1.GetNodeStatusRequest
	25, // 31: tailbus.v1.AgentAPI.WatchActivity:input_type -> tailbus.v1.WatchActivityRequest
	32, // 32: tailbus.v1.AgentAPI.GetTrace:input_type -> tailbus.v1.GetTraceRequest
	2,  // 33: tailbus.v1.AgentAPI.Register:output_type -> tailbus.v1.RegisterResponse
	4,  // 34: tailbus.v1.AgentAPI.IntrospectHandle:output_type -> tailbus.v1.IntrospectHandleResponse
	6,  // 35: tailbus.v1.AgentAPI.ListHandles:output_type -> tailbus.v1.ListHandlesResponse
	9,  // 36: tailbus.v1.AgentAPI.OpenSession:output_type -> tailbus.v1.OpenSessionResponse
	11, // 37: tailbus.v1.AgentAPI.SendMessage:output_type -> tailbus.v1.SendMessageResponse
	13, // 38: tailbus.v1.AgentAPI.Subscribe:output_type -> tailbus.v1.IncomingMessage
	15, // 39: tailbus.v1.AgentAPI.ResolveSession:output_type -> tailbus.v1.ResolveSessionResponse
	17, // 40: tailbus.v1.AgentAPI.ListSessions:output_type -> tailbus.v1.ListSessionsResponse
	20, // 41: tailbus.v1.AgentAPI.GetNodeStatus:output_type -> tailbus.v1.GetNodeStatusResponse
	26, // 42: tailbus.v1.AgentAPI.WatchActivity:output_type -> tailbus.v1.ActivityEvent
	33, // 43: tailbus.v1.AgentAPI.GetTrace:output_type -> tailbus.v1.GetTraceResponse
	33, // [33:44] is the sub-list for method output_type
	22, // [22:33] is the sub-list for method input_type
	22, // [22:22] is the sub-list for extension type_name
	22, // [22:22] is the sub-list for extension extendee
	0,  // [0:22] is the sub-list for field type_name
}

func init() { file_tailbus_v1_agent_proto_init() }
func file_tailbus_v1_agent_proto_init() {
	if File_tailbus_v1_agent_proto != nil {
		return
	}
	file_tailbus_v1_agent_proto_msgTypes[25].OneofWrappers = []any{
		(*ActivityEvent_MessageRouted)(nil),
		(*ActivityEvent_SessionOpened)(nil),
		(*ActivityEvent_SessionResolved)(nil),
		(*ActivityEvent_HandleRegistered)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_tailbus_v1_agent_proto_rawDesc), len(file_tailbus_v1_agent_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   34,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_tailbus_v1_agent_proto_goTypes,
		DependencyIndexes: file_tailbus_v1_agent_proto_depIdxs,
		EnumInfos:         file_tailbus_v1_agent_proto_enumTypes,
		MessageInfos:      file_tailbus_v1_agent_proto_msgTypes,
	}.Build()
	File_tailbus_v1_agent_proto = out.File
	file_tailbus_v1_agent_proto_goTypes = nil
	file_tailbus_v1_agent_proto_depIdxs = nil
}
